CREATE TABLE IF NOT EXISTS `users` (
    `id` bigint(20) NOT NULL,
    `firstName` varchar(255) NOT NULL,
    `lastName` varchar(255) NOT NULL,
    `email` varchar(255) NOT NULL,
    `password` varchar(255) NOT NULL,
    `salt` varchar(255) NOT NULL,
    `tokens` JSON NOT NULL DEFAULT '[]',
    `ranks` JSON NOT NULL DEFAULT '["user"]',
    `isBanned` tinyint(1) NOT NULL,
    `isActivated` tinyint(1) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
ALTER TABLE `users`
ADD PRIMARY KEY (`id`);
CREATE TABLE IF NOT EXISTS `verifyaccount` (
    `id` bigint(20) NOT NULL,
    `userId` bigint(20) NOT NULL,
    `hash` varchar(255) NOT NULL,
    `isUsed` tinyint(1) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
ALTER TABLE `verifyaccount`
ADD PRIMARY KEY (`id`, `userId`);
-- publication
CREATE TABLE IF NOT EXISTS `publication` (
    `id` bigint(20) NOT NULL,
    `userId` bigint(20) NOT NULL,
    `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `title` varchar(255) NOT NULL,
    `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `footer` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
-- create table wojewodztwa
CREATE TABLE IF NOT EXISTS `wojewodztwa` (
    `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` varchar(255) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
-- create table powiaty
CREATE TABLE IF NOT EXISTS `powiaty` (
    `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `wojId` int(11) NOT NULL -- ,FOREIGN KEY (wojId) REFERENCES wojewodztwa(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
-- create table gminy
CREATE TABLE IF NOT EXISTS `gminy` (
    `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `powId` int(11) NOT NULL -- ,FOREIGN KEY (powId) REFERENCES powiaty(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
-- answers
CREATE TABLE IF NOT EXISTS `answers` (
    `id` bigint(20) NOT NULL PRIMARY KEY,
    `publicationId` bigint(20) NOT NULL,
    `publicationReplyId` bigint(20) NOT NULL,
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
-- get powiaty.name and wojewodztwa.name from gminy where id = 1
SELECT gminy.name,
    powiaty.name,
    wojewodztwa.name
FROM gminy
    INNER JOIN powiaty ON gminy.powId = powiaty.id
    INNER JOIN wojewodztwa ON powiaty.wojId = wojewodztwa.id
WHERE gminy.id = 1;
-- data
INSERT INTO wojewodztwa (name)
VALUES ('dolnośląskie'),
    ('kujawsko-pomorskie'),
    ('lubelskie'),
    ('lubuskie'),
    ('łódzkie'),
    ('małopolskie'),
    ('mazowieckie'),
    ('opolskie'),
    ('podkarpackie'),
    ('podlaskie'),
    ('pomorskie'),
    ('śląskie'),
    ('świętokrzyskie'),
    ('warmińsko-mazurskie'),
    ('wielkopolskie'),
    ('zachodniopomorskie');
INSERT INTO powiaty (name, wojId)
VALUES ('bolesławiecki', 1),
    ('dzierżoniowski', 1),
    ('głogowski', 1),
    ('górowski', 1),
    ('jaworski', 1),
    ('karkonoski', 1),
    ('kamiennogórski', 1),
    ('kłodzki', 1),
    ('legnicki', 1),
    ('lubański', 1),
    ('lubiński', 1),
    ('lwówecki', 1),
    ('milicki', 1),
    ('oleśnicki', 1),
    ('oławski', 1),
    ('polkowicki', 1),
    ('strzeliński', 1),
    ('średzki (województwo dolnośląskie)', 1),
    ('świdnicki (województwo dolnośląskie)', 1),
    ('trzebnicki', 1),
    ('wałbrzyski', 1),
    ('wołowski', 1),
    ('wrocławski', 1),
    ('ząbkowicki', 1),
    ('zgorzelecki', 1),
    ('złotoryjski', 1),
    ('Jelenia Góra', 1),
    ('Legnica', 1),
    ('Wrocław', 1),
    ('Wałbrzych', 1),
    ('aleksandrowski', 2),
    ('brodnicki', 2),
    ('bydgoski', 2),
    ('chełmiński', 2),
    ('golubsko-dobrzyński', 2),
    ('grudziądzki', 2),
    ('inowrocławski', 2),
    ('lipnowski', 2),
    ('mogileński', 2),
    ('nakielski', 2),
    ('radziejowski', 2),
    ('rypiński', 2),
    ('sępoleński', 2),
    ('świecki', 2),
    ('toruński', 2),
    ('tucholski', 2),
    ('wąbrzeski', 2),
    ('włocławski', 2),
    ('żniński', 2),
    ('Bydgoszcz', 2),
    ('Grudziądz', 2),
    ('Toruń', 2),
    ('Włocławek', 2),
    ('bialski', 3),
    ('biłgorajski', 3),
    ('chełmski', 3),
    ('hrubieszowski', 3),
    ('janowski', 3),
    ('krasnostawski', 3),
    ('kraśnicki', 3),
    ('lubartowski', 3),
    ('lubelski', 3),
    ('łęczyński', 3),
    ('łukowski', 3),
    ('opolski (województwo lubelskie)', 3),
    ('parczewski', 3),
    ('puławski', 3),
    ('radzyński', 3),
    ('rycki', 3),
    ('świdnicki (województwo lubelskie)', 3),
    ('tomaszowski (województwo lubelskie)', 3),
    ('włodawski', 3),
    ('zamojski', 3),
    ('Biała Podlaska', 3),
    ('Chełm', 3),
    ('Lublin', 3),
    ('Zamość', 3),
    ('gorzowski', 4),
    ('krośnieński (województwo lubuskie)', 4),
    ('międzyrzecki', 4),
    ('nowosolski', 4),
    ('słubicki', 4),
    ('strzelecko-drezdenecki', 4),
    ('sulęciński', 4),
    ('świebodziński', 4),
    ('zielonogórski', 4),
    ('żagański', 4),
    ('żarski', 4),
    ('wschowski', 4),
    ('Gorzów Wielkopolski', 4),
    ('Zielona Góra', 4),
    ('bełchatowski', 5),
    ('kutnowski', 5),
    ('łaski', 5),
    ('łęczycki', 5),
    ('łowicki', 5),
    ('łódzki wschodni', 5),
    ('opoczyński', 5),
    ('pabianicki', 5),
    ('pajęczański', 5),
    ('piotrkowski', 5),
    ('poddębicki', 5),
    ('radomszczański', 5),
    ('rawski', 5),
    ('sieradzki', 5),
    ('skierniewicki', 5),
    ('tomaszowski (województwo łódzkie)', 5),
    ('wieluński', 5),
    ('wieruszowski', 5),
    ('zduńskowolski', 5),
    ('zgierski', 5),
    ('brzeziński', 5),
    ('Łódź', 5),
    ('Piotrków Trybunalski', 5),
    ('Skierniewice', 5),
    ('bocheński', 6),
    ('brzeski (województwo małopolskie)', 6),
    ('chrzanowski', 6),
    ('dąbrowski', 6),
    ('gorlicki', 6),
    ('krakowski', 6),
    ('limanowski', 6),
    ('miechowski', 6),
    ('myślenicki', 6),
    ('nowosądecki', 6),
    ('nowotarski', 6),
    ('olkuski', 6),
    ('oświęcimski', 6),
    ('proszowicki', 6),
    ('suski', 6),
    ('tarnowski', 6),
    ('tatrzański', 6),
    ('wadowicki', 6),
    ('wielicki', 6),
    ('Kraków', 6),
    ('Nowy Sącz', 6),
    ('Tarnów', 6),
    ('białobrzeski', 7),
    ('ciechanowski', 7),
    ('garwoliński', 7),
    ('gostyniński', 7),
    ('grodziski (województwo mazowieckie)', 7),
    ('grójecki', 7),
    ('kozienicki', 7),
    ('legionowski', 7),
    ('lipski', 7),
    ('łosicki', 7),
    ('makowski', 7),
    ('miński', 7),
    ('mławski', 7),
    ('nowodworski (województwo mazowieckie)', 7),
    ('ostrołęcki', 7),
    ('ostrowski (województwo mazowieckie)', 7),
    ('otwocki', 7),
    ('piaseczyński', 7),
    ('płocki', 7),
    ('płoński', 7),
    ('pruszkowski', 7),
    ('przasnyski', 7),
    ('przysuski', 7),
    ('pułtuski', 7),
    ('radomski', 7),
    ('siedlecki', 7),
    ('sierpecki', 7),
    ('sochaczewski', 7),
    ('sokołowski', 7),
    ('szydłowiecki', 7),
    ('warszawski zachodni', 7),
    ('węgrowski', 7),
    ('wołomiński', 7),
    ('wyszkowski', 7),
    ('zwoleński', 7),
    ('żuromiński', 7),
    ('żyrardowski', 7),
    ('Ostrołęka', 7),
    ('Płock', 7),
    ('Radom', 7),
    ('Siedlce', 7),
    ('Warszawa', 7),
    ('brzeski (województwo opolskie)', 8),
    ('głubczycki', 8),
    ('kędzierzyńsko-kozielski', 8),
    ('kluczborski', 8),
    ('krapkowicki', 8),
    ('namysłowski', 8),
    ('nyski', 8),
    ('oleski', 8),
    ('opolski (województwo opolskie)', 8),
    ('prudnicki', 8),
    ('strzelecki', 8),
    ('Opole', 8),
    ('bieszczadzki', 9),
    ('brzozowski', 9),
    ('dębicki', 9),
    ('jarosławski', 9),
    ('jasielski', 9),
    ('kolbuszowski', 9),
    ('krośnieński (województwo podkarpackie)', 9),
    ('leżajski', 9),
    ('lubaczowski', 9),
    ('łańcucki', 9),
    ('mielecki', 9),
    ('niżański', 9),
    ('przemyski', 9),
    ('przeworski', 9),
    ('ropczycko-sędziszowski', 9),
    ('rzeszowski', 9),
    ('sanocki', 9),
    ('stalowowolski', 9),
    ('strzyżowski', 9),
    ('tarnobrzeski', 9),
    ('leski', 9),
    ('Krosno', 9),
    ('Przemyśl', 9),
    ('Rzeszów', 9),
    ('Tarnobrzeg', 9),
    ('augustowski', 10),
    ('białostocki', 10),
    ('bielski (województwo podlaskie)', 10),
    ('grajewski', 10),
    ('hajnowski', 10),
    ('kolneński', 10),
    ('łomżyński', 10),
    ('moniecki', 10),
    ('sejneński', 10),
    ('siemiatycki', 10),
    ('sokólski', 10),
    ('suwalski', 10),
    ('wysokomazowiecki', 10),
    ('zambrowski', 10),
    ('Białystok', 10),
    ('Łomża', 10),
    ('Suwałki', 10),
    ('bytowski', 11),
    ('chojnicki', 11),
    ('człuchowski', 11),
    ('gdański', 11),
    ('kartuski', 11),
    ('kościerski', 11),
    ('kwidzyński', 11),
    ('lęborski', 11),
    ('malborski', 11),
    ('nowodworski (województwo pomorskie)', 11),
    ('pucki', 11),
    ('słupski', 11),
    ('starogardzki', 11),
    ('tczewski', 11),
    ('wejherowski', 11),
    ('sztumski', 11),
    ('Gdańsk', 11),
    ('Gdynia', 11),
    ('Słupsk', 11),
    ('Sopot', 11),
    ('będziński', 12),
    ('bielski (województwo śląskie)', 12),
    ('cieszyński', 12),
    ('częstochowski', 12),
    ('gliwicki', 12),
    ('kłobucki', 12),
    ('lubliniecki', 12),
    ('mikołowski', 12),
    ('myszkowski', 12),
    ('pszczyński', 12),
    ('raciborski', 12),
    ('rybnicki', 12),
    ('tarnogórski', 12),
    ('bieruńsko-lędziński', 12),
    ('wodzisławski', 12),
    ('zawierciański', 12),
    ('żywiecki', 12),
    ('Bielsko-Biała', 12),
    ('Bytom', 12),
    ('Chorzów', 12),
    ('Częstochowa', 12),
    ('Dąbrowa Górnicza', 12),
    ('Gliwice', 12),
    ('Jastrzębie-Zdrój', 12),
    ('Jaworzno', 12),
    ('Katowice', 12),
    ('Mysłowice', 12),
    ('Piekary Śląskie', 12),
    ('Ruda Śląska', 12),
    ('Rybnik', 12),
    ('Siemianowice Śląskie', 12),
    ('Sosnowiec', 12),
    ('Świętochłowice', 12),
    ('Tychy', 12),
    ('Zabrze', 12),
    ('Żory', 12),
    ('buski', 13),
    ('jędrzejowski', 13),
    ('kazimierski', 13),
    ('kielecki', 13),
    ('konecki', 13),
    ('opatowski', 13),
    ('ostrowiecki', 13),
    ('pińczowski', 13),
    ('sandomierski', 13),
    ('skarżyski', 13),
    ('starachowicki', 13),
    ('staszowski', 13),
    ('włoszczowski', 13),
    ('Kielce', 13),
    ('bartoszycki', 14),
    ('braniewski', 14),
    ('działdowski', 14),
    ('elbląski', 14),
    ('ełcki', 14),
    ('giżycki', 14),
    ('iławski', 14),
    ('kętrzyński', 14),
    ('lidzbarski', 14),
    ('mrągowski', 14),
    ('nidzicki', 14),
    ('nowomiejski', 14),
    ('olecki', 14),
    ('olsztyński', 14),
    ('ostródzki', 14),
    ('piski', 14),
    ('szczycieński', 14),
    ('gołdapski', 14),
    ('węgorzewski', 14),
    ('Elbląg', 14),
    ('Olsztyn', 14),
    ('chodzieski', 15),
    ('czarnkowsko-trzcianecki', 15),
    ('gnieźnieński', 15),
    ('gostyński', 15),
    ('grodziski (województwo wielkopolskie)', 15),
    ('jarociński', 15),
    ('kaliski', 15),
    ('kępiński', 15),
    ('kolski', 15),
    ('koniński', 15),
    ('kościański', 15),
    ('krotoszyński', 15),
    ('leszczyński', 15),
    ('międzychodzki', 15),
    ('nowotomyski', 15),
    ('obornicki', 15),
    ('ostrowski (województwo wielkopolskie)', 15),
    ('ostrzeszowski', 15),
    ('pilski', 15),
    ('pleszewski', 15),
    ('poznański', 15),
    ('rawicki', 15),
    ('słupecki', 15),
    ('szamotulski', 15),
    ('średzki (województwo wielkopolskie)', 15),
    ('śremski', 15),
    ('turecki', 15),
    ('wągrowiecki', 15),
    ('wolsztyński', 15),
    ('wrzesiński', 15),
    ('złotowski', 15),
    ('Kalisz', 15),
    ('Konin', 15),
    ('Leszno', 15),
    ('Poznań', 15),
    ('białogardzki', 16),
    ('choszczeński', 16),
    ('drawski', 16),
    ('goleniowski', 16),
    ('gryficki', 16),
    ('gryfiński', 16),
    ('kamieński', 16),
    ('kołobrzeski', 16),
    ('koszaliński', 16),
    ('myśliborski', 16),
    ('policki', 16),
    ('pyrzycki', 16),
    ('sławieński', 16),
    ('stargardzki', 16),
    ('szczecinecki', 16),
    ('świdwiński', 16),
    ('wałecki', 16),
    ('łobeski', 16),
    ('Koszalin', 16),
    ('Szczecin', 16),
    ('Świnoujście', 16);
INSERT INTO gminy (name, powId)
VALUES ('Bolesławiec', 1),
    (
        'Bolesławiec (gmina wiejska w województwie dolnośląskim)',
        1
    ),
    ('Gromadka', 1),
    ('Nowogrodziec', 1),
    ('Osiecznica', 1),
    ('Warta Bolesławiecka', 1),
    ('Bielawa', 2),
    ('Dzierżoniów', 2),
    ('Pieszyce', 2),
    ('Piława Górna', 2),
    ('Dzierżoniów (gmina wiejska)', 2),
    ('Łagiewniki', 2),
    ('Niemcza', 2),
    ('Głogów', 3),
    ('Głogów (gmina wiejska)', 3),
    ('Jerzmanowa', 3),
    ('Kotla', 3),
    ('Pęcław', 3),
    ('Żukowice', 3),
    ('Góra', 4),
    ('Jemielno', 4),
    ('Niechlów', 4),
    ('Wąsosz (gmina w województwie dolnośląskim)', 4),
    ('Jawor (miasto)', 5),
    ('Bolków', 5),
    ('Męcinka', 5),
    ('Mściwojów', 5),
    ('Paszowice', 5),
    ('Wądroże Wielkie', 5),
    ('Karpacz', 6),
    ('Kowary', 6),
    ('Piechowice', 6),
    ('Szklarska Poręba', 6),
    ('Janowice Wielkie', 6),
    ('Jeżów Sudecki', 6),
    ('Mysłakowice', 6),
    ('Podgórzyn', 6),
    ('Stara Kamienica', 6),
    ('Kamienna Góra', 7),
    ('Kamienna Góra (gmina wiejska)', 7),
    ('Lubawka', 7),
    ('Marciszów', 7),
    ('Duszniki-Zdrój', 8),
    ('Kłodzko', 8),
    ('Kudowa-Zdrój', 8),
    ('Nowa Ruda', 8),
    ('Polanica-Zdrój', 8),
    ('Bystrzyca Kłodzka', 8),
    ('Kłodzko (gmina wiejska)', 8),
    ('Lądek-Zdrój', 8),
    ('Lewin Kłodzki', 8),
    ('Międzylesie', 8),
    ('Nowa Ruda (gmina wiejska)', 8),
    ('Radków (gmina w województwie dolnośląskim)', 8),
    ('Stronie Śląskie', 8),
    ('Szczytna', 8),
    ('Chojnów', 9),
    ('Chojnów (gmina wiejska)', 9),
    ('Krotoszyce', 9),
    ('Kunice', 9),
    ('Legnickie Pole', 9),
    ('Miłkowice', 9),
    ('Prochowice', 9),
    ('Ruja', 9),
    ('Lubań (województwo dolnośląskie)', 10),
    ('Świeradów-Zdrój', 10),
    ('Leśna', 10),
    ('Lubań (gmina wiejska)', 10),
    ('Olszyna', 10),
    ('Platerówka', 10),
    ('Siekierczyn', 10),
    ('Lubin', 11),
    ('Lubin (gmina wiejska)', 11),
    ('Rudna', 11),
    ('Ścinawa', 11),
    ('Gryfów Śląski', 12),
    ('Lubomierz', 12),
    ('Lwówek Śląski', 12),
    ('Mirsk', 12),
    ('Wleń', 12),
    ('Cieszków', 13),
    ('Krośnice', 13),
    ('Milicz', 13),
    ('Oleśnica', 14),
    ('Bierutów', 14),
    ('Dobroszyce', 14),
    ('Dziadowa Kłoda', 14),
    ('Międzybórz', 14),
    (
        'Oleśnica (gmina wiejska w województwie dolnośląskim)',
        14
    ),
    ('Syców', 14),
    ('Twardogóra', 14),
    ('Oława', 15),
    ('Domaniów', 15),
    ('Jelcz-Laskowice', 15),
    ('Oława (gmina wiejska)', 15),
    ('Chocianów', 16),
    ('Gaworzyce', 16),
    ('Grębocice', 16),
    ('Polkowice', 16),
    ('Przemków', 16),
    ('Radwanice', 16),
    ('Borów', 17),
    ('Kondratowice', 17),
    ('Przeworno', 17),
    ('Strzelin', 17),
    ('Wiązów', 17),
    ('Kostomłoty', 18),
    ('Malczyce', 18),
    ('Miękinia', 18),
    ('Środa Śląska', 18),
    ('Udanin', 18),
    ('Świdnica', 19),
    ('Świebodzice', 19),
    ('Dobromierz', 19),
    ('Jaworzyna Śląska', 19),
    ('Marcinowice', 19),
    ('Strzegom', 19),
    (
        'Świdnica (gmina wiejska w województwie dolnośląskim)',
        19
    ),
    ('Żarów', 19),
    ('Oborniki Śląskie', 20),
    ('Prusice', 20),
    ('Trzebnica', 20),
    ('Wisznia Mała', 20),
    ('Zawonia', 20),
    ('Żmigród', 20),
    ('Boguszów-Gorce', 21),
    ('Jedlina-Zdrój', 21),
    ('Szczawno-Zdrój', 21),
    ('Czarny Bór (gmina w powiecie wałbrzyskim)', 21),
    ('Głuszyca', 21),
    ('Mieroszów', 21),
    ('Stare Bogaczowice', 21),
    ('Walim', 21),
    ('Brzeg Dolny', 22),
    ('Wińsko', 22),
    ('Wołów', 22),
    ('Czernica', 23),
    ('Długołęka', 23),
    ('Jordanów Śląski', 23),
    ('Kąty Wrocławskie', 23),
    ('Kobierzyce', 23),
    ('Mietków', 23),
    ('Sobótka', 23),
    ('Siechnice', 23),
    ('Żórawina', 23),
    ('Bardo', 24),
    ('Ciepłowody', 24),
    ('Kamieniec Ząbkowicki', 24),
    ('Stoszowice', 24),
    ('Ząbkowice Śląskie', 24),
    ('Ziębice', 24),
    ('Złoty Stok', 24),
    ('Zawidów', 25),
    ('Zgorzelec', 25),
    ('Bogatynia', 25),
    ('Pieńsk', 25),
    ('Sulików', 25),
    ('Węgliniec', 25),
    ('Zgorzelec (gmina wiejska)', 25),
    ('Wojcieszów', 26),
    ('Złotoryja', 26),
    ('Pielgrzymka', 26),
    ('Świerzawa', 26),
    ('Zagrodno', 26),
    ('Złotoryja (gmina wiejska)', 26),
    ('Jelenia Góra', 27),
    ('Legnica', 28),
    ('Wrocław', 29),
    ('Wałbrzych', 30),
    ('Aleksandrów Kujawski', 31),
    ('Ciechocinek', 31),
    ('Nieszawa', 31),
    ('Aleksandrów Kujawski (gmina wiejska)', 31),
    ('Bądkowo', 31),
    ('Koneck', 31),
    ('Raciążek', 31),
    ('Waganiec', 31),
    (
        'Zakrzewo (gmina w województwie kujawsko-pomorskim)',
        31
    ),
    ('Brodnica', 32),
    ('Bobrowo', 32),
    (
        'Brodnica (gmina wiejska w województwie kujawsko-pomorskim)',
        32
    ),
    ('Brzozie', 32),
    (
        'Górzno (gmina w województwie kujawsko-pomorskim)',
        32
    ),
    ('Bartniczka', 32),
    ('Jabłonowo Pomorskie', 32),
    (
        'Osiek (gmina w województwie kujawsko-pomorskim)',
        32
    ),
    ('Świedziebnia', 32),
    ('Zbiczno', 32),
    ('Białe Błota', 33),
    ('Dąbrowa Chełmińska', 33),
    ('Dobrcz', 33),
    ('Koronowo', 33),
    ('Nowa Wieś Wielka', 33),
    ('Osielsko', 33),
    ('Sicienko', 33),
    ('Solec Kujawski', 33),
    ('Chełmno', 34),
    ('Chełmno (gmina wiejska)', 34),
    ('Kijewo Królewskie', 34),
    ('Lisewo', 34),
    ('Papowo Biskupie', 34),
    ('Stolno', 34),
    ('Unisław', 34),
    ('Golub-Dobrzyń', 35),
    ('Ciechocin', 35),
    ('Golub-Dobrzyń (gmina wiejska)', 35),
    ('Kowalewo Pomorskie', 35),
    ('Radomin', 35),
    ('Zbójno', 35),
    ('Grudziądz (gmina wiejska)', 36),
    ('Gruta', 36),
    ('Łasin', 36),
    ('Radzyń Chełmiński', 36),
    ('Rogóźno', 36),
    ('Świecie nad Osą', 36),
    ('Inowrocław', 37),
    ('Dąbrowa Biskupia', 37),
    ('Gniewkowo', 37),
    ('Inowrocław (gmina wiejska)', 37),
    ('Janikowo', 37),
    ('Kruszwica', 37),
    ('Pakość', 37),
    ('Rojewo', 37),
    ('Złotniki Kujawskie', 37),
    ('Lipno', 38),
    (
        'Bobrowniki (gmina w województwie kujawsko-pomorskim)',
        38
    ),
    ('Chrostkowo', 38),
    ('Dobrzyń nad Wisłą', 38),
    ('Kikół', 38),
    (
        'Lipno (gmina wiejska w województwie kujawsko-pomorskim)',
        38
    ),
    ('Skępe', 38),
    ('Tłuchowo', 38),
    ('Wielgie', 38),
    (
        'Dąbrowa (gmina w województwie kujawsko-pomorskim)',
        39
    ),
    ('Jeziora Wielkie', 39),
    ('Mogilno', 39),
    ('Strzelno', 39),
    ('Kcynia', 40),
    ('Mrocza', 40),
    ('Nakło nad Notecią', 40),
    ('Sadki', 40),
    ('Szubin', 40),
    ('Radziejów', 41),
    ('Bytoń', 41),
    (
        'Dobre (gmina w województwie kujawsko-pomorskim)',
        41
    ),
    ('Osięciny', 41),
    ('Piotrków Kujawski', 41),
    ('Radziejów (gmina wiejska)', 41),
    ('Topólka', 41),
    ('Rypin', 42),
    ('Brzuze', 42),
    ('Rogowo (gmina w powiecie rypińskim)', 42),
    ('Rypin (gmina wiejska)', 42),
    ('Skrwilno', 42),
    ('Wąpielsk', 42),
    ('Kamień Krajeński', 43),
    ('Sępólno Krajeńskie', 43),
    ('Sośno', 43),
    ('Więcbork', 43),
    ('Bukowiec', 44),
    ('Dragacz', 44),
    ('Drzycim', 44),
    ('Jeżewo', 44),
    ('Lniano', 44),
    ('Nowe', 44),
    ('Osie', 44),
    ('Pruszcz', 44),
    ('Świecie', 44),
    ('Świekatowo', 44),
    ('Warlubie', 44),
    ('Chełmża', 45),
    ('Chełmża (gmina wiejska)', 45),
    ('Czernikowo', 45),
    ('Lubicz', 45),
    ('Łubianka', 45),
    ('Łysomice', 45),
    ('Obrowo', 45),
    ('Wielka Nieszawka', 45),
    ('Zławieś Wielka', 45),
    ('Cekcyn', 46),
    ('Gostycyn', 46),
    ('Kęsowo', 46),
    ('Lubiewo', 46),
    ('Śliwice', 46),
    ('Tuchola', 46),
    ('Wąbrzeźno', 47),
    ('Dębowa Łąka', 47),
    ('Książki', 47),
    ('Płużnica', 47),
    ('Ryńsk', 47),
    ('Kowal (miasto)', 48),
    ('Baruchowo', 48),
    ('Boniewo', 48),
    ('Brześć Kujawski', 48),
    ('Choceń', 48),
    ('Chodecz', 48),
    ('Fabianki', 48),
    ('Izbica Kujawska', 48),
    ('Kowal (gmina wiejska)', 48),
    ('Lubanie', 48),
    ('Lubień Kujawski', 48),
    ('Lubraniec', 48),
    ('Włocławek (gmina wiejska)', 48),
    ('Barcin', 49),
    ('Gąsawa', 49),
    ('Janowiec Wielkopolski', 49),
    ('Łabiszyn', 49),
    ('Rogowo (gmina w powiecie żnińskim)', 49),
    ('Żnin', 49),
    ('Bydgoszcz', 50),
    ('Grudziądz', 51),
    ('Toruń', 52),
    ('Włocławek', 53),
    ('Międzyrzec Podlaski', 54),
    ('Terespol', 54),
    ('Biała Podlaska (gmina wiejska)', 54),
    ('Drelów', 54),
    ('Janów Podlaski', 54),
    ('Kodeń', 54),
    ('Konstantynów', 54),
    ('Leśna Podlaska', 54),
    ('Łomazy', 54),
    ('Międzyrzec Podlaski (gmina wiejska)', 54),
    ('Piszczac', 54),
    ('Rokitno', 54),
    ('Rossosz', 54),
    ('Sławatycze', 54),
    ('Sosnówka', 54),
    ('Terespol (gmina wiejska)', 54),
    ('Tuczna', 54),
    ('Wisznice', 54),
    ('Zalesie', 54),
    ('Biłgoraj', 55),
    (
        'Aleksandrów (gmina w województwie lubelskim)',
        55
    ),
    ('Biłgoraj (gmina wiejska)', 55),
    ('Biszcza', 55),
    ('Frampol', 55),
    ('Goraj', 55),
    ('Józefów (gmina w województwie lubelskim)', 55),
    ('Księżpol', 55),
    ('Łukowa', 55),
    ('Obsza', 55),
    ('Potok Górny', 55),
    ('Tarnogród', 55),
    ('Tereszpol', 55),
    ('Turobin', 55),
    ('Rejowiec Fabryczny', 56),
    ('Białopole', 56),
    ('Chełm (gmina wiejska)', 56),
    ('Dorohusk', 56),
    ('Dubienka', 56),
    ('Kamień (gmina w województwie lubelskim)', 56),
    ('Leśniowice', 56),
    ('Rejowiec Fabryczny (gmina wiejska)', 56),
    ('Ruda-Huta', 56),
    ('Sawin', 56),
    ('Siedliszcze', 56),
    ('Wierzbica (gmina w województwie lubelskim)', 56),
    ('Wojsławice', 56),
    ('Żmudź', 56),
    ('Rejowiec', 56),
    ('Hrubieszów', 57),
    ('Dołhobyczów', 57),
    ('Horodło', 57),
    ('Hrubieszów (gmina wiejska)', 57),
    ('Mircze', 57),
    ('Trzeszczany', 57),
    ('Uchanie', 57),
    ('Werbkowice', 57),
    ('Batorz', 58),
    ('Chrzanów (gmina w województwie lubelskim)', 58),
    ('Dzwola', 58),
    ('Godziszów', 58),
    ('Janów Lubelski', 58),
    ('Modliborzyce', 58),
    ('Potok Wielki', 58),
    ('Krasnystaw', 59),
    ('Fajsławice', 59),
    ('Gorzków', 59),
    ('Izbica', 59),
    ('Krasnystaw (gmina wiejska)', 59),
    ('Kraśniczyn', 59),
    ('Łopiennik Górny', 59),
    ('Rudnik (gmina w województwie lubelskim)', 59),
    ('Siennica Różana', 59),
    ('Żółkiewka', 59),
    ('Kraśnik', 60),
    ('Annopol', 60),
    ('Dzierzkowice', 60),
    ('Gościeradów', 60),
    ('Kraśnik (gmina wiejska)', 60),
    ('Szastarka', 60),
    ('Trzydnik Duży', 60),
    ('Urzędów', 60),
    ('Wilkołaz', 60),
    ('Zakrzówek', 60),
    ('Lubartów', 61),
    ('Abramów', 61),
    ('Firlej', 61),
    ('Jeziorzany', 61),
    ('Kamionka (gmina wiejska)', 61),
    ('Kock', 61),
    ('Lubartów (gmina wiejska)', 61),
    ('Michów', 61),
    ('Niedźwiada', 61),
    ('Ostrów Lubelski', 61),
    ('Ostrówek (gmina w województwie lubelskim)', 61),
    ('Serniki', 61),
    ('Uścimów', 61),
    ('Bełżyce', 62),
    ('Borzechów', 62),
    ('Bychawa', 62),
    ('Garbów', 62),
    ('Głusk', 62),
    ('Jabłonna (gmina w województwie lubelskim)', 62),
    ('Jastków', 62),
    ('Konopnica (gmina w województwie lubelskim)', 62),
    ('Krzczonów', 62),
    ('Niedrzwica Duża', 62),
    ('Niemce', 62),
    ('Strzyżewice', 62),
    ('Wojciechów', 62),
    ('Wólka', 62),
    ('Wysokie', 62),
    ('Zakrzew (gmina w województwie lubelskim)', 62),
    ('Cyców', 63),
    ('Ludwin', 63),
    ('Łęczna', 63),
    ('Milejów', 63),
    ('Puchaczów', 63),
    ('Spiczyn', 63),
    ('Łuków', 64),
    ('Stoczek Łukowski', 64),
    ('Adamów (gmina w powiecie łukowskim)', 64),
    ('Krzywda', 64),
    ('Łuków (gmina wiejska)', 64),
    ('Serokomla', 64),
    ('Stanin', 64),
    ('Stoczek Łukowski (gmina wiejska)', 64),
    ('Trzebieszów', 64),
    ('Wojcieszków', 64),
    ('Wola Mysłowska', 64),
    ('Chodel', 65),
    ('Józefów nad Wisłą', 65),
    ('Karczmiska', 65),
    ('Łaziska', 65),
    ('Opole Lubelskie', 65),
    ('Poniatowa', 65),
    ('Wilków (gmina w województwie lubelskim)', 65),
    ('Dębowa Kłoda', 66),
    ('Jabłoń', 66),
    ('Milanów', 66),
    ('Parczew', 66),
    ('Podedwórze', 66),
    ('Siemień', 66),
    ('Sosnowica', 66),
    ('Puławy', 67),
    ('Baranów (gmina w województwie lubelskim)', 67),
    ('Janowiec', 67),
    ('Kazimierz Dolny', 67),
    ('Końskowola', 67),
    ('Kurów', 67),
    ('Markuszów', 67),
    ('Nałęczów', 67),
    ('Puławy (gmina wiejska)', 67),
    ('Wąwolnica', 67),
    ('Żyrzyn', 67),
    ('Radzyń Podlaski', 68),
    ('Borki', 68),
    ('Czemierniki', 68),
    ('Kąkolewnica', 68),
    ('Komarówka Podlaska', 68),
    ('Radzyń Podlaski (gmina wiejska)', 68),
    ('Ulan-Majorat', 68),
    ('Wohyń', 68),
    ('Dęblin', 69),
    ('Kłoczew', 69),
    ('Nowodwór', 69),
    ('Ryki', 69),
    ('Stężyca (gmina w województwie lubelskim)', 69),
    ('Ułęż', 69),
    ('Świdnik', 70),
    ('Mełgiew', 70),
    ('Piaski (gmina w województwie lubelskim)', 70),
    ('Rybczewice', 70),
    ('Trawniki', 70),
    ('Tomaszów Lubelski', 71),
    ('Bełżec', 71),
    ('Jarczów', 71),
    ('Krynice', 71),
    ('Lubycza Królewska', 71),
    ('Łaszczów', 71),
    ('Rachanie', 71),
    ('Susiec', 71),
    ('Tarnawatka', 71),
    ('Telatyn', 71),
    ('Tomaszów Lubelski (gmina wiejska)', 71),
    ('Tyszowce', 71),
    ('Ulhówek', 71),
    ('Włodawa', 72),
    ('Hanna', 72),
    ('Hańsk', 72),
    ('Stary Brus', 72),
    ('Urszulin', 72),
    ('Włodawa (gmina wiejska)', 72),
    ('Wola Uhruska', 72),
    ('Wyryki', 72),
    ('Adamów (gmina w powiecie zamojskim)', 73),
    ('Grabowiec', 73),
    ('Komarów-Osada', 73),
    ('Krasnobród', 73),
    ('Łabunie', 73),
    ('Miączyn', 73),
    ('Nielisz', 73),
    ('Radecznica', 73),
    ('Sitno', 73),
    ('Skierbieszów', 73),
    ('Stary Zamość', 73),
    ('Sułów', 73),
    ('Szczebrzeszyn', 73),
    ('Zamość (gmina wiejska)', 73),
    ('Zwierzyniec', 73),
    ('Biała Podlaska', 74),
    ('Chełm', 75),
    ('Lublin', 76),
    ('Zamość', 77),
    ('Kostrzyn nad Odrą', 78),
    ('Bogdaniec', 78),
    ('Deszczno', 78),
    ('Kłodawa (gmina w województwie lubuskim)', 78),
    ('Lubiszyn', 78),
    ('Santok', 78),
    ('Witnica', 78),
    ('Gubin', 79),
    ('Bobrowice', 79),
    ('Bytnica', 79),
    ('Dąbie (gmina w województwie lubuskim)', 79),
    ('Gubin (gmina wiejska)', 79),
    ('Krosno Odrzańskie', 79),
    ('Maszewo (gmina w województwie lubuskim)', 79),
    ('Bledzew', 80),
    ('Międzyrzecz', 80),
    ('Przytoczna', 80),
    ('Pszczew', 80),
    ('Skwierzyna', 80),
    ('Trzciel', 80),
    ('Nowa Sól', 81),
    ('Bytom Odrzański', 81),
    ('Kolsko', 81),
    ('Kożuchów', 81),
    ('Nowa Sól (gmina wiejska)', 81),
    ('Nowe Miasteczko', 81),
    ('Otyń', 81),
    ('Siedlisko', 81),
    ('Cybinka', 82),
    ('Górzyca', 82),
    ('Ośno Lubuskie', 82),
    ('Rzepin', 82),
    ('Słubice (gmina w województwie lubuskim)', 82),
    ('Dobiegniew', 83),
    ('Drezdenko', 83),
    ('Stare Kurowo', 83),
    ('Strzelce Krajeńskie', 83),
    ('Zwierzyn', 83),
    ('Krzeszyce', 84),
    ('Lubniewice', 84),
    ('Słońsk', 84),
    ('Sulęcin', 84),
    ('Torzym', 84),
    ('Lubrza (gmina w województwie lubuskim)', 85),
    ('Łagów (gmina w województwie lubuskim)', 85),
    ('Skąpe', 85),
    ('Szczaniec', 85),
    ('Świebodzin', 85),
    ('Zbąszynek', 85),
    ('Babimost', 86),
    ('Bojadła', 86),
    ('Czerwieńsk', 86),
    ('Kargowa', 86),
    ('Nowogród Bobrzański', 86),
    ('Sulechów', 86),
    ('Świdnica (gmina w województwie lubuskim)', 86),
    ('Trzebiechów', 86),
    ('Zabór', 86),
    ('Gozdnica', 87),
    ('Żagań', 87),
    ('Brzeźnica (gmina w województwie lubuskim)', 87),
    ('Iłowa', 87),
    ('Małomice', 87),
    ('Niegosławice', 87),
    ('Szprotawa', 87),
    ('Wymiarki', 87),
    ('Żagań (gmina wiejska)', 87),
    ('Łęknica', 88),
    ('Żary', 88),
    ('Brody (gmina w województwie lubuskim)', 88),
    ('Jasień', 88),
    ('Lipinki Łużyckie', 88),
    ('Lubsko', 88),
    ('Przewóz', 88),
    ('Trzebiel', 88),
    ('Tuplice', 88),
    ('Żary (gmina wiejska)', 88),
    ('Sława', 89),
    ('Szlichtyngowa', 89),
    ('Wschowa', 89),
    ('Gorzów Wielkopolski', 90),
    ('Zielona Góra', 91),
    ('Bełchatów', 92),
    ('Bełchatów (gmina wiejska)', 92),
    ('Drużbice', 92),
    ('Kleszczów', 92),
    ('Kluki', 92),
    ('Rusiec', 92),
    ('Szczerców', 92),
    ('Zelów', 92),
    ('Kutno', 93),
    ('Bedlno', 93),
    ('Dąbrowice', 93),
    ('Krośniewice', 93),
    ('Krzyżanów', 93),
    ('Kutno (gmina wiejska)', 93),
    ('Łanięta', 93),
    ('Nowe Ostrowy', 93),
    ('Oporów', 93),
    ('Strzelce', 93),
    ('Żychlin', 93),
    ('Buczek', 94),
    ('Łask', 94),
    ('Sędziejowice', 94),
    ('Widawa', 94),
    ('Wodzierady', 94),
    ('Łęczyca', 95),
    ('Daszyna', 95),
    ('Góra Świętej Małgorzaty', 95),
    ('Grabów', 95),
    ('Łęczyca (gmina wiejska)', 95),
    ('Piątek', 95),
    ('Świnice Warckie', 95),
    ('Witonia', 95),
    ('Łowicz', 96),
    ('Bielawy', 96),
    ('Chąśno', 96),
    ('Domaniewice', 96),
    ('Kiernozia', 96),
    ('Kocierzew Południowy', 96),
    ('Łowicz (gmina wiejska)', 96),
    ('Łyszkowice', 96),
    ('Nieborów', 96),
    ('Zduny (gmina w województwie łódzkim)', 96),
    ('Andrespol', 97),
    ('Brójce', 97),
    ('Koluszki', 97),
    ('Nowosolna', 97),
    ('Rzgów (gmina w województwie łódzkim)', 97),
    ('Tuszyn', 97),
    ('Białaczów', 98),
    ('Drzewica', 98),
    ('Mniszków', 98),
    ('Opoczno', 98),
    ('Paradyż', 98),
    ('Poświętne (gmina w województwie łódzkim)', 98),
    ('Sławno (gmina w województwie łódzkim)', 98),
    ('Żarnów', 98),
    ('Konstantynów Łódzki', 99),
    ('Pabianice', 99),
    ('Dłutów', 99),
    ('Dobroń', 99),
    ('Ksawerów', 99),
    ('Lutomiersk', 99),
    ('Pabianice (gmina wiejska)', 99),
    ('Działoszyn', 100),
    ('Kiełczygłów', 100),
    ('Nowa Brzeźnica', 100),
    ('Pajęczno', 100),
    ('Rząśnia', 100),
    ('Siemkowice', 100),
    ('Strzelce Wielkie', 100),
    ('Sulmierzyce (gmina wiejska)', 100),
    (
        'Aleksandrów (gmina w województwie łódzkim)',
        101
    ),
    ('Czarnocin (gmina w województwie łódzkim)', 101),
    ('Gorzkowice', 101),
    ('Grabica', 101),
    ('Łęki Szlacheckie', 101),
    (
        'Moszczenica (gmina w województwie łódzkim)',
        101
    ),
    ('Ręczno', 101),
    ('Rozprza', 101),
    ('Sulejów', 101),
    ('Wola Krzysztoporska', 101),
    ('Wolbórz', 101),
    ('Dalików', 102),
    ('Pęczniew', 102),
    ('Poddębice', 102),
    ('Uniejów', 102),
    ('Wartkowice', 102),
    ('Zadzim', 102),
    ('Radomsko', 103),
    ('Dobryszyce', 103),
    ('Gidle', 103),
    ('Gomunice', 103),
    ('Kamieńsk', 103),
    ('Kobiele Wielkie', 103),
    ('Kodrąb', 103),
    ('Lgota Wielka', 103),
    ('Ładzice', 103),
    ('Masłowice', 103),
    ('Przedbórz', 103),
    ('Radomsko (gmina wiejska)', 103),
    ('Wielgomłyny', 103),
    ('Żytno', 103),
    ('Rawa Mazowiecka', 104),
    ('Biała Rawska', 104),
    ('Cielądz', 104),
    ('Rawa Mazowiecka (gmina wiejska)', 104),
    ('Regnów', 104),
    ('Sadkowice', 104),
    ('Sieradz', 105),
    ('Błaszki', 105),
    ('Brąszewice', 105),
    ('Brzeźnio', 105),
    ('Burzenin', 105),
    ('Goszczanów', 105),
    ('Klonowa', 105),
    ('Sieradz (gmina wiejska)', 105),
    ('Warta', 105),
    ('Wróblew', 105),
    ('Złoczew', 105),
    ('Bolimów', 106),
    ('Głuchów', 106),
    ('Godzianów', 106),
    ('Kowiesy', 106),
    ('Lipce Reymontowskie', 106),
    ('Maków', 106),
    ('Nowy Kawęczyn', 106),
    ('Skierniewice (gmina wiejska)', 106),
    ('Słupia (gmina w województwie łódzkim)', 106),
    ('Tomaszów Mazowiecki', 107),
    ('Będków', 107),
    ('Budziszewice', 107),
    ('Czerniewice', 107),
    ('Inowłódz', 107),
    ('Lubochnia', 107),
    ('Rokiciny', 107),
    ('Rzeczyca', 107),
    ('Tomaszów Mazowiecki (gmina wiejska)', 107),
    ('Ujazd (gmina w województwie łódzkim)', 107),
    ('Żelechlinek', 107),
    ('Biała (gmina w województwie łódzkim)', 108),
    ('Czarnożyły', 108),
    (
        'Konopnica (gmina w województwie lubelskim)',
        108
    ),
    ('Mokrsko', 108),
    ('Osjaków', 108),
    ('Ostrówek (gmina w województwie łódzkim)', 108),
    ('Pątnów', 108),
    ('Skomlin', 108),
    ('Wieluń', 108),
    ('Wierzchlas', 108),
    (
        'Bolesławiec (gmina w województwie łódzkim)',
        109
    ),
    ('Czastary', 109),
    ('Galewice', 109),
    ('Lututów', 109),
    ('Łubnice (gmina w województwie łódzkim)', 109),
    ('Sokolniki', 109),
    ('Wieruszów', 109),
    ('Zduńska Wola', 110),
    ('Szadek', 110),
    ('Zapolice', 110),
    ('Zduńska Wola (gmina wiejska)', 110),
    ('Głowno', 111),
    ('Ozorków', 111),
    ('Zgierz', 111),
    ('Aleksandrów Łódzki', 111),
    ('Głowno (gmina wiejska)', 111),
    ('Ozorków (gmina wiejska)', 111),
    ('Parzęczew', 111),
    ('Stryków', 111),
    ('Zgierz (gmina wiejska)', 111),
    ('Brzeziny', 112),
    (
        'Brzeziny (gmina wiejska w województwie łódzkim)',
        112
    ),
    ('Dmosin', 112),
    ('Jeżów', 112),
    ('Rogów', 112),
    ('Łódź', 113),
    ('Piotrków Trybunalski', 114),
    ('Skierniewice', 115),
    ('Bochnia', 116),
    ('Bochnia (gmina wiejska)', 116),
    ('Drwinia', 116),
    ('Lipnica Murowana', 116),
    ('Łapanów', 116),
    ('Nowy Wiśnicz', 116),
    ('Rzezawa', 116),
    ('Trzciana', 116),
    ('Żegocina', 116),
    ('Borzęcin', 117),
    ('Brzesko', 117),
    ('Czchów', 117),
    ('Dębno (gmina w województwie małopolskim)', 117),
    ('Gnojnik', 117),
    ('Iwkowa', 117),
    ('Szczurowa', 117),
    ('Alwernia', 118),
    ('Babice', 118),
    (
        'Chrzanów (gmina w województwie małopolskim)',
        118
    ),
    ('Libiąż', 118),
    ('Trzebinia', 118),
    ('Bolesław (gmina w powiecie dąbrowskim)', 119),
    ('Dąbrowa Tarnowska', 119),
    ('Gręboszów', 119),
    ('Mędrzechów', 119),
    ('Olesno (gmina w województwie małopolskim)', 119),
    ('Radgoszcz', 119),
    ('Szczucin', 119),
    ('Gorlice', 120),
    ('Biecz', 120),
    ('Bobowa', 120),
    ('Gorlice (gmina wiejska)', 120),
    ('Lipinki', 120),
    ('Łużna', 120),
    (
        'Moszczenica (gmina w województwie małopolskim)',
        120
    ),
    ('Ropa', 120),
    ('Sękowa', 120),
    ('Uście Gorlickie', 120),
    (
        'Czernichów (gmina w województwie małopolskim)',
        121
    ),
    ('Igołomia-Wawrzeńczyce', 121),
    ('Iwanowice', 121),
    ('Jerzmanowice-Przeginia', 121),
    ('Kocmyrzów-Luborzyca', 121),
    ('Krzeszowice', 121),
    ('Liszki', 121),
    (
        'Michałowice (gmina w województwie małopolskim)',
        121
    ),
    ('Mogilany', 121),
    ('Skała', 121),
    ('Skawina', 121),
    ('Słomniki', 121),
    ('Sułoszowa', 121),
    ('Świątniki Górne', 121),
    ('Wielka Wieś', 121),
    ('Zabierzów', 121),
    ('Zielonki', 121),
    ('Limanowa', 122),
    ('Mszana Dolna', 122),
    ('Dobra (gmina w województwie małopolskim)', 122),
    ('Jodłownik', 122),
    ('Kamienica', 122),
    ('Laskowa', 122),
    ('Limanowa (gmina wiejska)', 122),
    ('Łukowica', 122),
    ('Mszana Dolna (gmina wiejska)', 122),
    ('Niedźwiedź', 122),
    ('Słopnice', 122),
    ('Tymbark', 122),
    ('Charsznica', 123),
    ('Gołcza', 123),
    ('Kozłów', 123),
    ('Książ Wielki', 123),
    ('Miechów', 123),
    ('Racławice', 123),
    ('Słaboszów', 123),
    ('Dobczyce', 124),
    ('Lubień', 124),
    ('Myślenice', 124),
    ('Pcim', 124),
    ('Raciechowice', 124),
    ('Siepraw', 124),
    ('Sułkowice', 124),
    ('Tokarnia', 124),
    (
        'Wiśniowa (gmina w województwie małopolskim)',
        124
    ),
    ('Grybów', 125),
    ('Chełmiec', 125),
    ('Gródek nad Dunajcem', 125),
    ('Grybów (gmina wiejska)', 125),
    ('Kamionka Wielka', 125),
    ('Korzenna', 125),
    ('Krynica-Zdrój', 125),
    ('Łabowa', 125),
    ('Łącko', 125),
    ('Łososina Dolna', 125),
    ('Muszyna', 125),
    ('Nawojowa', 125),
    ('Piwniczna-Zdrój', 125),
    ('Podegrodzie', 125),
    ('Rytro', 125),
    ('Stary Sącz', 125),
    ('Nowy Targ', 126),
    ('Szczawnica', 126),
    ('Czarny Dunajec', 126),
    ('Czorsztyn', 126),
    ('Jabłonka', 126),
    ('Krościenko nad Dunajcem', 126),
    ('Lipnica Wielka', 126),
    ('Łapsze Niżne', 126),
    ('Nowy Targ (gmina wiejska)', 126),
    ('Ochotnica Dolna', 126),
    ('Raba Wyżna', 126),
    ('Rabka-Zdrój', 126),
    ('Spytkowice (gmina w powiecie wadowickim)', 126),
    ('Szaflary', 126),
    ('Bukowno', 127),
    ('Bolesław (gmina w powiecie olkuskim)', 127),
    ('Klucze', 127),
    ('Olkusz', 127),
    ('Trzyciąż', 127),
    ('Wolbrom', 127),
    ('Oświęcim', 128),
    ('Brzeszcze', 128),
    ('Chełmek', 128),
    ('Kęty', 128),
    ('Osiek (gmina w województwie małopolskim)', 128),
    ('Oświęcim (gmina wiejska)', 128),
    ('Polanka Wielka', 128),
    ('Przeciszów', 128),
    ('Zator', 128),
    ('Koniusza', 129),
    ('Koszyce', 129),
    ('Nowe Brzesko', 129),
    ('Pałecznica', 129),
    ('Proszowice', 129),
    ('Radziemice', 129),
    ('Jordanów', 130),
    ('Sucha Beskidzka', 130),
    ('Budzów', 130),
    ('Bystra-Sidzina', 130),
    ('Jordanów (gmina wiejska)', 130),
    ('Maków Podhalański', 130),
    ('Stryszawa', 130),
    ('Zawoja', 130),
    ('Zembrzyce', 130),
    ('Ciężkowice', 131),
    ('Gromnik', 131),
    ('Lisia Góra', 131),
    ('Pleśna', 131),
    ('Radłów (gmina w województwie małopolskim)', 131),
    ('Ryglice', 131),
    ('Rzepiennik Strzyżewski', 131),
    ('Skrzyszów', 131),
    ('Tarnów (gmina wiejska)', 131),
    ('Tuchów', 131),
    ('Wierzchosławice', 131),
    ('Wietrzychowice', 131),
    ('Wojnicz', 131),
    ('Zakliczyn', 131),
    ('Żabno', 131),
    ('Szerzyny', 131),
    ('Zakopane', 132),
    ('Biały Dunajec', 132),
    ('Bukowina Tatrzańska', 132),
    ('Kościelisko', 132),
    ('Poronin', 132),
    ('Andrychów', 133),
    (
        'Brzeźnica (gmina w województwie małopolskim)',
        133
    ),
    ('Kalwaria Zebrzydowska', 133),
    ('Lanckorona', 133),
    ('Mucharz', 133),
    ('Spytkowice (gmina w powiecie wadowickim)', 133),
    ('Stryszów', 133),
    ('Tomice', 133),
    ('Wadowice', 133),
    ('Wieprz', 133),
    ('Biskupice', 134),
    ('Gdów', 134),
    ('Kłaj', 134),
    ('Niepołomice', 134),
    ('Wieliczka', 134),
    ('Kraków', 135),
    ('Nowy Sącz', 136),
    ('Tarnów', 137),
    (
        'Białobrzegi (gmina w województwie mazowieckim)',
        138
    ),
    ('Promna', 138),
    ('Radzanów (gmina w powiecie białobrzeskim)', 138),
    ('Stara Błotnica', 138),
    ('Stromiec', 138),
    ('Wyśmierzyce', 138),
    ('Ciechanów', 139),
    ('Ciechanów (gmina wiejska)', 139),
    ('Glinojeck', 139),
    ('Gołymin-Ośrodek', 139),
    ('Grudusk', 139),
    ('Ojrzeń', 139),
    ('Opinogóra Górna', 139),
    ('Regimin', 139),
    ('Sońsk', 139),
    ('Garwolin', 140),
    ('Łaskarzew', 140),
    ('Borowie', 140),
    ('Garwolin (gmina wiejska)', 140),
    ('Górzno (gmina w województwie mazowieckim)', 140),
    ('Łaskarzew (gmina wiejska)', 140),
    ('Maciejowice', 140),
    ('Miastków Kościelny', 140),
    ('Parysów', 140),
    ('Pilawa', 140),
    ('Sobolew', 140),
    ('Trojanów', 140),
    ('Wilga', 140),
    ('Żelechów', 140),
    ('Gostynin', 141),
    ('Gostynin (gmina wiejska)', 141),
    ('Pacyna', 141),
    ('Sanniki', 141),
    ('Szczawin Kościelny', 141),
    ('Milanówek', 142),
    ('Podkowa Leśna', 142),
    (
        'Baranów (gmina w województwie mazowieckim)',
        142
    ),
    ('Grodzisk Mazowiecki', 142),
    ('Jaktorów', 142),
    ('Żabia Wola', 142),
    ('Belsk Duży', 143),
    ('Błędów', 143),
    ('Chynów', 143),
    ('Goszczyn', 143),
    ('Grójec', 143),
    ('Jasieniec', 143),
    ('Mogielnica', 143),
    ('Nowe Miasto nad Pilicą', 143),
    ('Pniewy (gmina w województwie mazowieckim)', 143),
    ('Warka', 143),
    ('Garbatka-Letnisko', 144),
    ('Głowaczów', 144),
    ('Gniewoszów', 144),
    ('Grabów nad Pilicą', 144),
    ('Kozienice', 144),
    ('Magnuszew', 144),
    ('Sieciechów', 144),
    ('Legionowo', 145),
    (
        'Jabłonna (gmina w województwie mazowieckim)',
        145
    ),
    ('Nieporęt', 145),
    ('Serock', 145),
    ('Wieliszew', 145),
    ('Chotcza', 146),
    ('Ciepielów', 146),
    ('Lipsko', 146),
    ('Rzeczniów', 146),
    ('Sienno', 146),
    ('Solec nad Wisłą', 146),
    ('Huszlew', 147),
    ('Łosice', 147),
    (
        'Olszanka (gmina w województwie mazowieckim)',
        147
    ),
    ('Platerów', 147),
    ('Sarnaki', 147),
    ('Stara Kornica', 147),
    ('Maków Mazowiecki', 148),
    ('Czerwonka', 148),
    ('Karniewo', 148),
    ('Krasnosielc', 148),
    ('Młynarze', 148),
    ('Płoniawy-Bramura', 148),
    ('Różan', 148),
    ('Rzewnie', 148),
    ('Sypniewo', 148),
    ('Szelków', 148),
    ('Mińsk Mazowiecki', 149),
    ('Cegłów', 149),
    ('Dębe Wielkie', 149),
    ('Dobre (gmina w województwie mazowieckim)', 149),
    ('Halinów', 149),
    ('Jakubów', 149),
    ('Kałuszyn', 149),
    ('Latowicz', 149),
    ('Mińsk Mazowiecki (gmina wiejska)', 149),
    ('Mrozy', 149),
    ('Siennica', 149),
    ('Stanisławów', 149),
    ('Sulejówek', 149),
    ('Mława', 150),
    ('Dzierzgowo', 150),
    ('Lipowiec Kościelny', 150),
    ('Radzanów (gmina w powiecie mławskim)', 150),
    ('Strzegowo', 150),
    ('Stupsk', 150),
    ('Szreńsk', 150),
    (
        'Szydłowo (gmina w województwie mazowieckim)',
        150
    ),
    ('Wieczfnia Kościelna', 150),
    ('Wiśniewo', 150),
    ('Nowy Dwór Mazowiecki', 151),
    ('Czosnów', 151),
    ('Leoncin', 151),
    ('Nasielsk', 151),
    ('Pomiechówek', 151),
    ('Zakroczym', 151),
    ('Baranowo', 152),
    ('Czarnia', 152),
    ('Czerwin', 152),
    ('Goworowo', 152),
    ('Kadzidło', 152),
    ('Lelis', 152),
    ('Łyse', 152),
    ('Myszyniec', 152),
    ('Olszewo-Borki', 152),
    ('Rzekuń', 152),
    ('Troszyn', 152),
    ('Ostrów Mazowiecka', 153),
    ('Andrzejewo', 153),
    ('Boguty-Pianki', 153),
    ('Brok', 153),
    ('Małkinia Górna', 153),
    ('Nur', 153),
    ('Ostrów Mazowiecka (gmina wiejska)', 153),
    ('Stary Lubotyń', 153),
    ('Szulborze Wielkie', 153),
    ('Wąsewo', 153),
    ('Zaręby Kościelne', 153),
    ('Józefów (powiat otwocki)', 154),
    ('Otwock', 154),
    ('Celestynów', 154),
    ('Karczew', 154),
    ('Kołbiel', 154),
    ('Osieck', 154),
    ('Sobienie-Jeziory', 154),
    ('Wiązowna', 154),
    ('Góra Kalwaria', 155),
    ('Konstancin-Jeziorna', 155),
    ('Lesznowola', 155),
    ('Piaseczno', 155),
    ('Prażmów', 155),
    ('Tarczyn', 155),
    ('Bielsk', 156),
    ('Bodzanów', 156),
    ('Brudzeń Duży', 156),
    ('Bulkowo', 156),
    ('Drobin', 156),
    ('Gąbin', 156),
    ('Łąck', 156),
    ('Mała Wieś', 156),
    ('Nowy Duninów', 156),
    ('Radzanowo', 156),
    (
        'Słubice (gmina w województwie mazowieckim)',
        156
    ),
    ('Słupno', 156),
    ('Stara Biała', 156),
    ('Staroźreby', 156),
    ('Wyszogród', 156),
    ('Płońsk', 157),
    ('Raciąż', 157),
    ('Baboszewo', 157),
    ('Czerwińsk nad Wisłą', 157),
    ('Dzierzążnia', 157),
    ('Joniec', 157),
    ('Naruszewo', 157),
    ('Nowe Miasto', 157),
    ('Płońsk (gmina wiejska)', 157),
    ('Raciąż (gmina wiejska)', 157),
    ('Sochocin', 157),
    ('Załuski', 157),
    ('Piastów', 158),
    ('Pruszków', 158),
    ('Brwinów', 158),
    (
        'Michałowice (gmina w województwie mazowieckim)',
        158
    ),
    ('Nadarzyn', 158),
    ('Raszyn', 158),
    ('Przasnysz', 159),
    ('Chorzele', 159),
    ('Czernice Borowe', 159),
    ('Jednorożec', 159),
    ('Krasne (gmina w województwie mazowieckim)', 159),
    ('Krzynowłoga Mała', 159),
    ('Przasnysz (gmina wiejska)', 159),
    ('Borkowice', 160),
    ('Gielniów', 160),
    ('Klwów', 160),
    ('Odrzywół', 160),
    ('Potworów', 160),
    ('Przysucha', 160),
    ('Rusinów', 160),
    ('Wieniawa', 160),
    ('Gzy', 161),
    ('Obryte', 161),
    ('Pokrzywnica', 161),
    ('Pułtusk', 161),
    ('Świercze', 161),
    ('Winnica', 161),
    ('Zatory', 161),
    ('Pionki', 162),
    ('Gózd', 162),
    ('Iłża', 162),
    ('Jastrzębia', 162),
    ('Jedlińsk', 162),
    ('Jedlnia-Letnisko', 162),
    ('Kowala', 162),
    ('Pionki (gmina wiejska)', 162),
    ('Przytyk', 162),
    ('Skaryszew', 162),
    (
        'Wierzbica (gmina w województwie mazowieckim)',
        162
    ),
    ('Wolanów', 162),
    (
        'Zakrzew (gmina w województwie mazowieckim)',
        162
    ),
    ('Domanice', 163),
    ('Korczew', 163),
    ('Kotuń', 163),
    ('Mokobody', 163),
    ('Mordy', 163),
    ('Paprotnia', 163),
    ('Przesmyki', 163),
    ('Siedlce (gmina wiejska)', 163),
    ('Skórzec', 163),
    ('Suchożebry', 163),
    ('Wiśniew', 163),
    ('Wodynie', 163),
    ('Zbuczyn', 163),
    ('Sierpc', 164),
    ('Gozdowo', 164),
    ('Mochowo', 164),
    ('Rościszewo', 164),
    ('Sierpc (gmina wiejska)', 164),
    ('Szczutowo', 164),
    ('Zawidz', 164),
    ('Sochaczew', 165),
    ('Brochów', 165),
    ('Iłów', 165),
    ('Młodzieszyn', 165),
    ('Nowa Sucha', 165),
    ('Rybno (gmina w województwie mazowieckim)', 165),
    ('Sochaczew (gmina wiejska)', 165),
    ('Teresin', 165),
    ('Sokołów Podlaski', 166),
    ('Bielany', 166),
    ('Ceranów', 166),
    ('Jabłonna Lacka', 166),
    ('Kosów Lacki', 166),
    ('Repki', 166),
    ('Sabnie', 166),
    ('Sokołów Podlaski (gmina wiejska)', 166),
    ('Sterdyń', 166),
    ('Chlewiska', 167),
    ('Jastrząb', 167),
    ('Mirów', 167),
    ('Orońsko', 167),
    ('Szydłowiec', 167),
    ('Błonie', 168),
    ('Izabelin', 168),
    ('Kampinos', 168),
    ('Leszno (gmina wiejska)', 168),
    ('Łomianki', 168),
    ('Ożarów Mazowiecki', 168),
    ('Stare Babice', 168),
    ('Węgrów', 169),
    ('Grębków', 169),
    ('Korytnica', 169),
    ('Liw', 169),
    ('Łochów', 169),
    ('Miedzna', 169),
    ('Sadowne', 169),
    ('Stoczek', 169),
    ('Wierzbno', 169),
    ('Kobyłka', 170),
    ('Marki', 170),
    ('Ząbki', 170),
    ('Zielonka (powiat wołomiński)', 170),
    ('Dąbrówka', 170),
    ('Jadów', 170),
    ('Klembów', 170),
    (
        'Poświętne (gmina w województwie podlaskim)',
        170
    ),
    ('Radzymin', 170),
    ('Strachówka', 170),
    ('Tłuszcz', 170),
    ('Wołomin', 170),
    ('Brańszczyk', 171),
    ('Długosiodło', 171),
    ('Rząśnik', 171),
    ('Somianka', 171),
    ('Wyszków', 171),
    ('Zabrodzie', 171),
    ('Kazanów', 172),
    ('Policzna', 172),
    ('Przyłęk', 172),
    ('Tczów', 172),
    ('Zwoleń', 172),
    ('Bieżuń', 173),
    ('Kuczbork-Osada', 173),
    ('Lubowidz', 173),
    ('Lutocin', 173),
    ('Siemiątkowo', 173),
    ('Żuromin', 173),
    ('Żyrardów', 174),
    ('Mszczonów', 174),
    ('Puszcza Mariańska', 174),
    ('Radziejowice', 174),
    ('Wiskitki', 174),
    ('Ostrołęka', 175),
    ('Płock', 176),
    ('Radom', 177),
    ('Siedlce', 178),
    ('Warszawa', 179),
    ('Brzeg (miasto)', 180),
    ('Skarbimierz', 180),
    ('Grodków', 180),
    ('Lewin Brzeski', 180),
    ('Lubsza', 180),
    ('Olszanka (gmina w województwie opolskim)', 180),
    ('Baborów', 181),
    ('Branice', 181),
    ('Głubczyce', 181),
    ('Kietrz', 181),
    ('Kędzierzyn-Koźle', 182),
    ('Bierawa', 182),
    ('Cisek', 182),
    ('Pawłowiczki', 182),
    ('Polska Cerekiew', 182),
    ('Reńska Wieś', 182),
    ('Byczyna', 183),
    ('Kluczbork', 183),
    ('Lasowice Wielkie', 183),
    ('Wołczyn', 183),
    ('Gogolin', 184),
    ('Krapkowice', 184),
    ('Strzeleczki', 184),
    ('Walce', 184),
    ('Zdzieszowice', 184),
    ('Domaszowice', 185),
    ('Namysłów', 185),
    ('Pokój', 185),
    ('Świerczów', 185),
    ('Wilków (gmina w województwie opolskim)', 185),
    ('Głuchołazy', 186),
    ('Kamiennik', 186),
    ('Korfantów', 186),
    ('Łambinowice', 186),
    ('Nysa', 186),
    ('Otmuchów', 186),
    ('Paczków', 186),
    ('Pakosławice', 186),
    ('Skoroszyce', 186),
    ('Dobrodzień', 187),
    ('Gorzów Śląski', 187),
    ('Olesno (gmina w województwie opolskim)', 187),
    ('Praszka', 187),
    ('Radłów (gmina w województwie opolskim)', 187),
    ('Rudniki', 187),
    ('Zębowice', 187),
    ('Chrząstowice', 188),
    ('Dąbrowa (gmina w województwie opolskim)', 188),
    ('Dobrzeń Wielki', 188),
    ('Komprachcice', 188),
    ('Łubniany', 188),
    ('Murów', 188),
    ('Niemodlin', 188),
    ('Ozimek', 188),
    ('Popielów', 188),
    ('Prószków', 188),
    ('Tarnów Opolski', 188),
    ('Tułowice', 188),
    ('Turawa', 188),
    ('Biała (gmina w województwie opolskim)', 189),
    ('Głogówek', 189),
    ('Lubrza (gmina w województwie opolskim)', 189),
    ('Prudnik', 189),
    ('Izbicko', 190),
    ('Jemielnica', 190),
    ('Kolonowskie', 190),
    ('Leśnica', 190),
    ('Strzelce Opolskie', 190),
    ('Ujazd (gmina w województwie opolskim)', 190),
    ('Zawadzkie', 190),
    ('Opole', 191),
    ('Czarna (gmina w powiecie bieszczadzkim)', 192),
    ('Lutowiska', 192),
    ('Ustrzyki Dolne', 192),
    ('Brzozów', 193),
    ('Domaradz', 193),
    ('Dydnia', 193),
    ('Haczów', 193),
    ('Jasienica Rosielna', 193),
    ('Nozdrzec', 193),
    ('Dębica', 194),
    ('Brzostek', 194),
    ('Czarna (gmina w powiecie dębickim)', 194),
    ('Dębica (gmina wiejska)', 194),
    ('Jodłowa', 194),
    ('Pilzno', 194),
    ('Żyraków', 194),
    ('Jarosław (województwo podkarpackie)', 195),
    ('Radymno', 195),
    ('Chłopice', 195),
    ('Jarosław (gmina wiejska)', 195),
    ('Laszki', 195),
    ('Pawłosiów', 195),
    ('Pruchnik', 195),
    ('Radymno (gmina wiejska)', 195),
    (
        'Rokietnica (gmina w województwie podkarpackim)',
        195
    ),
    ('Roźwienica', 195),
    ('Wiązownica', 195),
    ('Jasło', 196),
    ('Brzyska', 196),
    (
        'Dębowiec (gmina w województwie podkarpackim)',
        196
    ),
    ('Jasło (gmina wiejska)', 196),
    ('Kołaczyce', 196),
    ('Krempna', 196),
    ('Nowy Żmigród', 196),
    ('Osiek Jasielski', 196),
    ('Skołyszyn', 196),
    ('Tarnowiec', 196),
    ('Cmolas', 197),
    ('Kolbuszowa', 197),
    ('Majdan Królewski', 197),
    ('Niwiska', 197),
    ('Raniżów', 197),
    ('Dzikowiec', 197),
    ('Chorkówka', 198),
    ('Dukla', 198),
    ('Iwonicz-Zdrój', 198),
    ('Jedlicze', 198),
    ('Korczyna', 198),
    ('Krościenko Wyżne', 198),
    ('Miejsce Piastowe', 198),
    ('Rymanów', 198),
    ('Wojaszówka', 198),
    ('Jaśliska', 198),
    ('Leżajsk', 199),
    ('Grodzisko Dolne', 199),
    ('Kuryłówka', 199),
    ('Leżajsk (gmina wiejska)', 199),
    ('Nowa Sarzyna', 199),
    ('Lubaczów', 200),
    ('Cieszanów', 200),
    ('Horyniec-Zdrój', 200),
    ('Lubaczów (gmina wiejska)', 200),
    ('Narol', 200),
    ('Oleszyce', 200),
    ('Stary Dzików', 200),
    ('Wielkie Oczy', 200),
    ('Łańcut', 201),
    (
        'Białobrzegi (gmina w województwie podkarpackim)',
        201
    ),
    ('Czarna (gmina w powiecie łańcuckim)', 201),
    ('Łańcut (gmina wiejska)', 201),
    ('Markowa', 201),
    ('Rakszawa', 201),
    ('Żołynia', 201),
    ('Mielec', 202),
    ('Borowa', 202),
    (
        'Czermin (gmina w województwie podkarpackim)',
        202
    ),
    ('Gawłuszowice', 202),
    ('Mielec (gmina wiejska)', 202),
    ('Padew Narodowa', 202),
    ('Przecław', 202),
    ('Radomyśl Wielki', 202),
    ('Tuszów Narodowy', 202),
    ('Wadowice Górne', 202),
    ('Harasiuki', 203),
    (
        'Jarocin (gmina w województwie podkarpackim)',
        203
    ),
    ('Jeżowe', 203),
    ('Krzeszów', 203),
    ('Nisko', 203),
    ('Rudnik nad Sanem', 203),
    ('Ulanów', 203),
    ('Bircza', 204),
    ('Dubiecko', 204),
    ('Fredropol', 204),
    ('Krasiczyn', 204),
    ('Krzywcza', 204),
    ('Medyka', 204),
    ('Orły', 204),
    ('Przemyśl (gmina wiejska)', 204),
    ('Stubno', 204),
    ('Żurawica', 204),
    ('Przeworsk', 205),
    ('Adamówka', 205),
    ('Gać', 205),
    ('Jawornik Polski', 205),
    ('Kańczuga', 205),
    ('Przeworsk (gmina wiejska)', 205),
    ('Sieniawa', 205),
    ('Tryńcza', 205),
    ('Zarzecze', 205),
    ('Iwierzyce', 206),
    ('Ostrów', 206),
    ('Ropczyce', 206),
    ('Sędziszów Małopolski', 206),
    ('Wielopole Skrzyńskie', 206),
    ('Dynów', 207),
    ('Błażowa', 207),
    ('Boguchwała', 207),
    (
        'Chmielnik (gmina w województwie podkarpackim)',
        207
    ),
    ('Dynów (gmina wiejska)', 207),
    ('Głogów Małopolski', 207),
    ('Hyżne', 207),
    (
        'Kamień (gmina w województwie podkarpackim)',
        207
    ),
    (
        'Krasne (gmina w województwie podkarpackim)',
        207
    ),
    ('Lubenia', 207),
    ('Sokołów Małopolski', 207),
    ('Świlcza', 207),
    ('Trzebownisko', 207),
    ('Tyczyn', 207),
    ('Sanok', 208),
    ('Besko', 208),
    ('Bukowsko', 208),
    ('Komańcza', 208),
    ('Sanok (gmina wiejska)', 208),
    ('Tyrawa Wołoska', 208),
    ('Zagórz', 208),
    ('Zarszyn', 208),
    ('Stalowa Wola', 209),
    ('Bojanów', 209),
    ('Pysznica', 209),
    ('Radomyśl nad Sanem', 209),
    ('Zaklików', 209),
    ('Zaleszany', 209),
    ('Czudec', 210),
    ('Frysztak', 210),
    ('Niebylec', 210),
    ('Strzyżów', 210),
    (
        'Wiśniowa (gmina w województwie podkarpackim)',
        210
    ),
    ('Baranów Sandomierski', 211),
    (
        'Gorzyce (gmina w województwie podkarpackim)',
        211
    ),
    ('Grębów', 211),
    ('Nowa Dęba', 211),
    ('Baligród', 212),
    ('Cisna', 212),
    ('Lesko', 212),
    ('Olszanica', 212),
    ('Solina', 212),
    ('Krosno', 213),
    ('Przemyśl', 214),
    ('Rzeszów', 215),
    ('Tarnobrzeg', 216),
    ('Augustów', 217),
    ('Augustów (gmina wiejska)', 217),
    ('Bargłów Kościelny', 217),
    ('Lipsk', 217),
    ('Nowinka', 217),
    ('Płaska', 217),
    ('Sztabin', 217),
    ('Choroszcz', 218),
    ('Czarna Białostocka', 218),
    ('Dobrzyniewo Duże', 218),
    ('Gródek', 218),
    ('Juchnowiec Kościelny', 218),
    ('Łapy', 218),
    ('Michałowo', 218),
    (
        'Poświętne (gmina w województwie podlaskim)',
        218
    ),
    ('Supraśl', 218),
    ('Suraż', 218),
    ('Turośń Kościelna', 218),
    ('Tykocin', 218),
    ('Wasilków', 218),
    ('Zabłudów', 218),
    ('Zawady', 218),
    ('Bielsk Podlaski', 219),
    ('Brańsk', 219),
    ('Bielsk Podlaski (gmina wiejska)', 219),
    ('Boćki', 219),
    ('Brańsk (gmina wiejska)', 219),
    ('Orla', 219),
    ('Rudka', 219),
    ('Wyszki', 219),
    ('Grajewo', 220),
    ('Grajewo (gmina wiejska)', 220),
    ('Radziłów', 220),
    ('Rajgród', 220),
    ('Szczuczyn', 220),
    ('Wąsosz (gmina w województwie podlaskim)', 220),
    ('Hajnówka', 221),
    ('Białowieża', 221),
    ('Czeremcha', 221),
    ('Czyże', 221),
    ('Dubicze Cerkiewne', 221),
    ('Hajnówka (gmina wiejska)', 221),
    ('Kleszczele', 221),
    ('Narew', 221),
    ('Narewka', 221),
    ('Kolno', 222),
    ('Grabowo', 222),
    (
        'Kolno (gmina wiejska w województwie podlaskim)',
        222
    ),
    ('Mały Płock', 222),
    ('Stawiski', 222),
    ('Turośl', 222),
    ('Jedwabne', 223),
    ('Łomża (gmina wiejska)', 223),
    ('Miastkowo', 223),
    ('Nowogród', 223),
    ('Piątnica', 223),
    ('Przytuły', 223),
    ('Śniadowo', 223),
    ('Wizna', 223),
    ('Zbójna', 223),
    ('Goniądz', 224),
    ('Jasionówka', 224),
    ('Jaświły', 224),
    ('Knyszyn', 224),
    ('Krypno', 224),
    ('Mońki', 224),
    ('Trzcianne', 224),
    ('Sejny', 225),
    ('Giby', 225),
    ('Krasnopol', 225),
    ('Puńsk', 225),
    ('Sejny (gmina wiejska)', 225),
    ('Siemiatycze', 226),
    ('Drohiczyn', 226),
    ('Dziadkowice', 226),
    ('Grodzisk', 226),
    ('Mielnik', 226),
    ('Milejczyce', 226),
    ('Nurzec-Stacja', 226),
    ('Perlejewo', 226),
    ('Siemiatycze (gmina wiejska)', 226),
    ('Dąbrowa Białostocka', 227),
    ('Janów (gmina w województwie podlaskim)', 227),
    ('Korycin', 227),
    ('Krynki', 227),
    ('Kuźnica', 227),
    ('Nowy Dwór', 227),
    ('Sidra', 227),
    ('Sokółka', 227),
    ('Suchowola', 227),
    ('Szudziałowo', 227),
    ('Bakałarzewo', 228),
    ('Filipów', 228),
    ('Jeleniewo', 228),
    ('Przerośl', 228),
    ('Raczki', 228),
    ('Rutka-Tartak', 228),
    ('Suwałki (gmina wiejska)', 228),
    ('Szypliszki', 228),
    ('Wiżajny', 228),
    ('Wysokie Mazowieckie', 229),
    ('Ciechanowiec', 229),
    ('Czyżew', 229),
    ('Klukowo', 229),
    ('Kobylin-Borzymy', 229),
    ('Kulesze Kościelne', 229),
    ('Nowe Piekuty', 229),
    ('Sokoły', 229),
    ('Szepietowo', 229),
    ('Wysokie Mazowieckie (gmina wiejska)', 229),
    ('Zambrów', 230),
    ('Kołaki Kościelne', 230),
    ('Rutki', 230),
    ('Szumowo', 230),
    ('Zambrów (gmina wiejska)', 230),
    ('Białystok', 231),
    ('Łomża', 232),
    ('Suwałki', 233),
    ('Borzytuchom', 234),
    ('Bytów', 234),
    ('Czarna Dąbrówka', 234),
    ('Kołczygłowy', 234),
    ('Lipnica', 234),
    ('Miastko', 234),
    ('Parchowo', 234),
    ('Studzienice', 234),
    ('Trzebielino', 234),
    ('Tuchomie', 234),
    ('Chojnice', 235),
    ('Brusy', 235),
    ('Chojnice (gmina wiejska)', 235),
    ('Czersk', 235),
    ('Konarzyny', 235),
    ('Człuchów', 236),
    ('Czarne', 236),
    ('Człuchów (gmina wiejska)', 236),
    ('Debrzno', 236),
    ('Koczała', 236),
    ('Przechlewo', 236),
    ('Rzeczenica', 236),
    ('Pruszcz Gdański', 237),
    ('Cedry Wielkie', 237),
    ('Kolbudy', 237),
    ('Pruszcz Gdański (gmina wiejska)', 237),
    ('Przywidz', 237),
    ('Pszczółki', 237),
    ('Suchy Dąb', 237),
    ('Trąbki Wielkie', 237),
    ('Chmielno', 238),
    ('Kartuzy', 238),
    ('Przodkowo', 238),
    ('Sierakowice', 238),
    ('Somonino', 238),
    ('Stężyca (gmina w województwie pomorskim)', 238),
    ('Sulęczyno', 238),
    ('Żukowo', 238),
    ('Kościerzyna', 239),
    ('Dziemiany', 239),
    ('Karsin', 239),
    ('Kościerzyna (gmina wiejska)', 239),
    ('Liniewo', 239),
    ('Lipusz', 239),
    ('Nowa Karczma', 239),
    ('Stara Kiszewa', 239),
    ('Kwidzyn', 240),
    ('Gardeja', 240),
    ('Kwidzyn (gmina wiejska)', 240),
    ('Prabuty', 240),
    ('Ryjewo', 240),
    ('Sadlinki', 240),
    ('Lębork', 241),
    ('Łeba', 241),
    ('Cewice', 241),
    ('Nowa Wieś Lęborska', 241),
    ('Wicko', 241),
    ('Malbork', 242),
    ('Lichnowy', 242),
    ('Malbork (gmina wiejska)', 242),
    ('Miłoradz', 242),
    ('Nowy Staw', 242),
    ('Stare Pole', 242),
    ('Krynica Morska', 243),
    ('Nowy Dwór Gdański', 243),
    ('Ostaszewo', 243),
    ('Stegna', 243),
    ('Sztutowo', 243),
    ('Hel (miasto)', 244),
    ('Gmina Jastarnia', 244),
    ('Puck', 244),
    ('Władysławowo', 244),
    ('Kosakowo', 244),
    ('Krokowa', 244),
    ('Puck (gmina wiejska)', 244),
    ('Ustka', 245),
    ('Damnica', 245),
    ('Dębnica Kaszubska', 245),
    ('Główczyce', 245),
    ('Kępice', 245),
    ('Kobylnica', 245),
    ('Potęgowo', 245),
    ('Słupsk (gmina wiejska)', 245),
    ('Smołdzino', 245),
    ('Ustka (gmina wiejska)', 245),
    ('Czarna Woda', 246),
    ('Skórcz', 246),
    ('Starogard Gdański', 246),
    ('Bobowo', 246),
    ('Kaliska', 246),
    ('Lubichowo', 246),
    ('Osieczna (gmina w województwie pomorskim)', 246),
    ('Osiek (gmina w województwie pomorskim)', 246),
    ('Skarszewy', 246),
    ('Skórcz (gmina wiejska)', 246),
    ('Smętowo Graniczne', 246),
    ('Starogard Gdański (gmina wiejska)', 246),
    ('Zblewo', 246),
    ('Tczew', 247),
    ('Gniew', 247),
    ('Morzeszczyn', 247),
    ('Pelplin', 247),
    ('Subkowy', 247),
    ('Tczew (gmina wiejska)', 247),
    ('Reda (miasto)', 248),
    ('Rumia', 248),
    ('Wejherowo', 248),
    ('Choczewo', 248),
    ('Gniewino', 248),
    ('Linia', 248),
    ('Luzino', 248),
    ('Łęczyce', 248),
    ('Szemud', 248),
    ('Wejherowo (gmina wiejska)', 248),
    ('Dzierzgoń', 249),
    ('Mikołajki Pomorskie', 249),
    ('Stary Dzierzgoń', 249),
    ('Stary Targ', 249),
    ('Sztum', 249),
    ('Gdańsk', 250),
    ('Gdynia', 251),
    ('Słupsk', 252),
    ('Sopot', 253),
    ('Będzin', 254),
    ('Czeladź (miasto)', 254),
    ('Wojkowice', 254),
    ('Bobrowniki (gmina w województwie śląskim)', 254),
    ('Mierzęcice', 254),
    ('Psary', 254),
    ('Siewierz', 254),
    ('Sławków (województwo śląskie)', 254),
    ('Szczyrk', 255),
    ('Bestwina', 255),
    ('Buczkowice', 255),
    ('Czechowice-Dziedzice', 255),
    ('Jasienica', 255),
    ('Jaworze', 255),
    ('Kozy', 255),
    ('Porąbka', 255),
    ('Wilamowice', 255),
    ('Wilkowice', 255),
    ('Cieszyn', 256),
    ('Ustroń', 256),
    ('Wisła (miasto)', 256),
    ('Brenna', 256),
    ('Chybie', 256),
    ('Dębowiec (gmina w województwie śląskim)', 256),
    ('Goleszów', 256),
    ('Hażlach', 256),
    ('Istebna', 256),
    ('Skoczów', 256),
    ('Strumień', 256),
    ('Zebrzydowice', 256),
    ('Blachownia', 257),
    ('Dąbrowa Zielona', 257),
    ('Janów (gmina w województwie śląskim)', 257),
    ('Kamienica Polska', 257),
    ('Kłomnice', 257),
    ('Koniecpol', 257),
    ('Konopiska', 257),
    ('Kruszyna', 257),
    ('Lelów', 257),
    ('Mstów', 257),
    ('Mykanów', 257),
    ('Olsztyn (gmina w województwie śląskim)', 257),
    ('Poczesna', 257),
    ('Przyrów', 257),
    ('Rędziny', 257),
    ('Starcza', 257),
    ('Knurów', 258),
    ('Pyskowice', 258),
    ('Gierałtowice', 258),
    ('Pilchowice', 258),
    ('Rudziniec', 258),
    ('Sośnicowice', 258),
    ('Toszek', 258),
    ('Wielowieś', 258),
    ('Kłobuck', 259),
    ('Krzepice', 259),
    ('Lipie', 259),
    ('Miedźno', 259),
    ('Opatów (gmina w województwie śląskim)', 259),
    ('Panki', 259),
    ('Popów', 259),
    ('Przystajń', 259),
    ('Wręczyca Wielka', 259),
    ('Lubliniec', 260),
    ('Boronów', 260),
    ('Ciasna', 260),
    ('Herby', 260),
    ('Kochanowice', 260),
    ('Koszęcin', 260),
    ('Pawonków', 260),
    ('Woźniki', 260),
    ('Łaziska Górne', 261),
    ('Mikołów', 261),
    ('Orzesze', 261),
    ('Ornontowice', 261),
    ('Wyry', 261),
    ('Myszków', 262),
    ('Koziegłowy', 262),
    ('Niegowa', 262),
    ('Poraj', 262),
    ('Żarki', 262),
    ('Goczałkowice-Zdrój', 263),
    ('Kobiór', 263),
    ('Miedźna', 263),
    ('Pawłowice', 263),
    ('Pszczyna', 263),
    ('Suszec', 263),
    ('Racibórz', 264),
    ('Kornowac', 264),
    ('Krzanowice', 264),
    ('Krzyżanowice', 264),
    ('Kuźnia Raciborska', 264),
    ('Nędza', 264),
    ('Pietrowice Wielkie', 264),
    ('Rudnik (gmina w województwie śląskim)', 264),
    ('Czerwionka-Leszczyny', 265),
    ('Gaszowice', 265),
    ('Jejkowice', 265),
    ('Lyski', 265),
    ('Świerklany', 265),
    ('Kalety', 266),
    ('Miasteczko Śląskie', 266),
    ('Radzionków', 266),
    ('Tarnowskie Góry', 266),
    ('Krupski Młyn', 266),
    ('Ożarowice', 266),
    ('Świerklaniec', 266),
    ('Tworóg', 266),
    ('Zbrosławice', 266),
    ('Bieruń', 267),
    ('Imielin', 267),
    ('Lędziny', 267),
    ('Bojszowy', 267),
    ('Chełm Śląski', 267),
    ('Pszów', 268),
    ('Radlin', 268),
    ('Rydułtowy', 268),
    ('Wodzisław Śląski', 268),
    ('Godów', 268),
    ('Gorzyce (gmina w województwie śląskim)', 268),
    ('Lubomia', 268),
    ('Marklowice', 268),
    ('Mszana', 268),
    ('Poręba', 269),
    ('Zawiercie', 269),
    ('Irządze', 269),
    ('Kroczyce', 269),
    ('Łazy', 269),
    ('Ogrodzieniec', 269),
    ('Pilica', 269),
    ('Szczekociny', 269),
    ('Włodowice', 269),
    ('Żarnowiec', 269),
    ('Żywiec', 270),
    ('Czernichów (gmina w województwie śląskim)', 270),
    ('Gilowice', 270),
    ('Jeleśnia', 270),
    ('Koszarawa', 270),
    ('Lipowa', 270),
    ('Łękawica', 270),
    ('Łodygowice', 270),
    ('Milówka', 270),
    ('Radziechowy-Wieprz', 270),
    ('Rajcza', 270),
    ('Ślemień', 270),
    ('Świnna', 270),
    ('Ujsoły', 270),
    ('Węgierska Górka', 270),
    ('Bielsko-Biała', 271),
    ('Bytom', 272),
    ('Chorzów', 273),
    ('Częstochowa', 274),
    ('Dąbrowa Górnicza', 275),
    ('Gliwice', 276),
    ('Jastrzębie-Zdrój', 277),
    ('Jaworzno', 278),
    ('Katowice', 279),
    ('Mysłowice', 280),
    ('Piekary Śląskie', 281),
    ('Ruda Śląska', 282),
    ('Rybnik', 283),
    ('Siemianowice Śląskie', 284),
    ('Sosnowiec', 285),
    ('Świętochłowice', 286),
    ('Tychy', 287),
    ('Zabrze', 288),
    ('Żory', 289),
    ('Busko-Zdrój', 290),
    ('Gnojno', 290),
    ('Nowy Korczyn', 290),
    ('Pacanów', 290),
    ('Solec-Zdrój', 290),
    ('Stopnica', 290),
    ('Tuczępy', 290),
    ('Wiślica', 290),
    ('Imielno', 291),
    ('Jędrzejów', 291),
    ('Małogoszcz', 291),
    ('Nagłowice', 291),
    ('Oksa', 291),
    ('Sędziszów', 291),
    (
        'Słupia (gmina w województwie świętokrzyskim)',
        291
    ),
    ('Sobków', 291),
    ('Wodzisław', 291),
    ('Bejsce', 292),
    (
        'Czarnocin (gmina w województwie świętokrzyskim)',
        292
    ),
    ('Kazimierza Wielka', 292),
    ('Opatowiec', 292),
    ('Skalbmierz', 292),
    ('Bieliny', 293),
    ('Bodzentyn', 293),
    ('Chęciny', 293),
    (
        'Chmielnik (gmina w województwie świętokrzyskim)',
        293
    ),
    ('Daleszyce', 293),
    ('Górno', 293),
    (
        'Łagów (gmina w województwie świętokrzyskim)',
        293
    ),
    ('Łopuszno', 293),
    ('Masłów', 293),
    ('Miedziana Góra', 293),
    ('Mniów', 293),
    ('Morawica', 293),
    ('Nowa Słupia', 293),
    ('Piekoszów', 293),
    ('Pierzchnica', 293),
    ('Raków', 293),
    ('Nowiny', 293),
    ('Strawczyn', 293),
    ('Zagnańsk', 293),
    ('Fałków', 294),
    ('Gowarczów', 294),
    ('Końskie', 294),
    ('Radoszyce', 294),
    ('Ruda Maleniecka', 294),
    ('Słupia Konecka', 294),
    ('Smyków', 294),
    ('Stąporków', 294),
    ('Baćkowice', 295),
    ('Iwaniska', 295),
    ('Lipnik', 295),
    (
        'Opatów (gmina w województwie świętokrzyskim)',
        295
    ),
    ('Ożarów', 295),
    ('Sadowie', 295),
    ('Tarłów', 295),
    ('Wojciechowice', 295),
    ('Ostrowiec Świętokrzyski', 296),
    ('Bałtów', 296),
    ('Bodzechów', 296),
    ('Ćmielów', 296),
    ('Kunów', 296),
    ('Waśniów', 296),
    ('Działoszyce', 297),
    ('Kije', 297),
    ('Michałów', 297),
    ('Pińczów', 297),
    ('Złota', 297),
    ('Sandomierz', 298),
    ('Dwikozy', 298),
    ('Klimontów', 298),
    ('Koprzywnica', 298),
    ('Łoniów', 298),
    ('Obrazów', 298),
    ('Samborzec', 298),
    ('Wilczyce', 298),
    ('Zawichost', 298),
    ('Skarżysko-Kamienna', 299),
    ('Bliżyn', 299),
    ('Łączna', 299),
    ('Skarżysko Kościelne', 299),
    ('Suchedniów', 299),
    ('Starachowice', 300),
    (
        'Brody (gmina w województwie świętokrzyskim)',
        300
    ),
    ('Mirzec', 300),
    ('Pawłów', 300),
    ('Wąchock', 300),
    ('Bogoria', 301),
    (
        'Łubnice (gmina w województwie świętokrzyskim)',
        301
    ),
    (
        'Oleśnica (gmina w województwie świętokrzyskim)',
        301
    ),
    (
        'Osiek (gmina w województwie świętokrzyskim)',
        301
    ),
    ('Połaniec', 301),
    ('Rytwiany', 301),
    ('Staszów', 301),
    ('Szydłów', 301),
    ('Kluczewsko', 302),
    ('Krasocin', 302),
    ('Moskorzew', 302),
    (
        'Radków (gmina w województwie świętokrzyskim)',
        302
    ),
    ('Secemin', 302),
    ('Włoszczowa', 302),
    ('Kielce', 303),
    ('Bartoszyce', 304),
    ('Górowo Iławeckie', 304),
    ('Bartoszyce (gmina wiejska)', 304),
    ('Bisztynek', 304),
    ('Górowo Iławeckie (gmina wiejska)', 304),
    ('Sępopol', 304),
    ('Braniewo', 305),
    ('Braniewo (gmina wiejska)', 305),
    ('Frombork', 305),
    ('Lelkowo', 305),
    ('Pieniężno', 305),
    ('Płoskinia', 305),
    ('Wilczęta', 305),
    ('Działdowo', 306),
    ('Działdowo (gmina wiejska)', 306),
    ('Iłowo-Osada', 306),
    ('Lidzbark', 306),
    ('Płośnica', 306),
    (
        'Rybno (gmina w województwie warmińsko-mazurskim)',
        306
    ),
    ('Elbląg (gmina wiejska)', 307),
    ('Godkowo', 307),
    ('Gronowo Elbląskie', 307),
    ('Markusy', 307),
    ('Milejewo', 307),
    ('Młynary', 307),
    ('Pasłęk', 307),
    ('Rychliki', 307),
    ('Tolkmicko', 307),
    ('Ełk', 308),
    ('Ełk (gmina wiejska)', 308),
    ('Kalinowo', 308),
    ('Prostki', 308),
    ('Stare Juchy', 308),
    ('Giżycko', 309),
    ('Giżycko (gmina wiejska)', 309),
    ('Kruklanki', 309),
    ('Miłki', 309),
    ('Ryn', 309),
    ('Wydminy', 309),
    ('Iława', 310),
    ('Lubawa', 310),
    ('Iława (gmina wiejska)', 310),
    ('Kisielice', 310),
    ('Lubawa (gmina wiejska)', 310),
    ('Susz', 310),
    ('Zalewo', 310),
    ('Kętrzyn', 311),
    ('Barciany', 311),
    ('Kętrzyn (gmina wiejska)', 311),
    ('Korsze', 311),
    ('Reszel', 311),
    ('Srokowo', 311),
    ('Lidzbark Warmiński', 312),
    ('Kiwity', 312),
    ('Lidzbark Warmiński (gmina wiejska)', 312),
    ('Lubomino', 312),
    ('Orneta', 312),
    ('Mrągowo', 313),
    ('Mikołajki', 313),
    ('Mrągowo (gmina wiejska)', 313),
    ('Piecki', 313),
    ('Sorkwity', 313),
    ('Janowiec Kościelny', 314),
    ('Janowo', 314),
    ('Kozłowo', 314),
    ('Nidzica', 314),
    ('Nowe Miasto Lubawskie', 315),
    ('Biskupiec (gmina w powiecie nowomiejskim)', 315),
    ('Grodziczno', 315),
    ('Kurzętnik', 315),
    ('Nowe Miasto Lubawskie (gmina wiejska)', 315),
    ('Kowale Oleckie', 316),
    ('Olecko', 316),
    ('Świętajno (gmina w powiecie oleckim)', 316),
    ('Wieliczki', 316),
    ('Barczewo', 317),
    ('Biskupiec (gmina w powiecie olsztyńskim)', 317),
    ('Dobre Miasto', 317),
    ('Dywity', 317),
    ('Gietrzwałd', 317),
    ('Jeziorany', 317),
    ('Jonkowo', 317),
    (
        'Kolno (gmina w województwie warmińsko-mazurskim)',
        317
    ),
    ('Olsztynek', 317),
    ('Purda', 317),
    ('Stawiguda', 317),
    ('Świątki', 317),
    ('Ostróda', 318),
    ('Dąbrówno', 318),
    ('Grunwald', 318),
    ('Łukta', 318),
    ('Małdyty', 318),
    ('Miłakowo', 318),
    ('Miłomłyn', 318),
    ('Morąg', 318),
    ('Ostróda (gmina wiejska)', 318),
    ('Biała Piska', 319),
    ('Orzysz', 319),
    ('Pisz', 319),
    ('Ruciane-Nida', 319),
    ('Szczytno', 320),
    ('Dźwierzuty', 320),
    ('Jedwabno', 320),
    ('Pasym', 320),
    ('Rozogi', 320),
    ('Szczytno (gmina wiejska)', 320),
    (
        'Świętajno (gmina w powiecie szczycieńskim)',
        320
    ),
    ('Wielbark', 320),
    ('Banie Mazurskie', 321),
    ('Dubeninki', 321),
    ('Gołdap', 321),
    ('Budry', 322),
    ('Pozezdrze', 322),
    ('Węgorzewo', 322),
    ('Elbląg', 323),
    ('Olsztyn', 324),
    ('Chodzież', 325),
    ('Budzyń', 325),
    ('Chodzież (gmina wiejska)', 325),
    ('Margonin', 325),
    ('Szamocin', 325),
    ('Czarnków', 326),
    ('Czarnków (gmina wiejska)', 326),
    ('Drawsko', 326),
    ('Krzyż Wielkopolski', 326),
    ('Lubasz', 326),
    ('Połajewo', 326),
    ('Trzcianka', 326),
    ('Wieleń', 326),
    ('Gniezno', 327),
    ('Czerniejewo', 327),
    ('Gniezno (gmina wiejska)', 327),
    ('Kiszkowo', 327),
    ('Kłecko', 327),
    ('Łubowo', 327),
    ('Mieleszyn', 327),
    ('Niechanowo', 327),
    ('Trzemeszno', 327),
    ('Witkowo', 327),
    ('Borek Wielkopolski', 328),
    ('Gostyń', 328),
    ('Krobia', 328),
    ('Pępowo', 328),
    (
        'Piaski (gmina w województwie wielkopolskim)',
        328
    ),
    ('Pogorzela', 328),
    ('Poniec', 328),
    ('Granowo', 329),
    ('Grodzisk Wielkopolski', 329),
    ('Kamieniec', 329),
    ('Rakoniewice', 329),
    ('Wielichowo', 329),
    ('Jaraczewo', 330),
    (
        'Jarocin (gmina w województwie wielkopolskim)',
        330
    ),
    ('Kotlin', 330),
    ('Żerków', 330),
    ('Blizanów', 331),
    (
        'Brzeziny (gmina w województwie wielkopolskim)',
        331
    ),
    ('Ceków-Kolonia', 331),
    ('Godziesze Wielkie', 331),
    ('Koźminek', 331),
    ('Lisków', 331),
    ('Mycielin', 331),
    ('Opatówek', 331),
    ('Stawiszyn', 331),
    ('Szczytniki', 331),
    ('Żelazków', 331),
    (
        'Baranów (gmina w województwie wielkopolskim)',
        332
    ),
    ('Bralin', 332),
    ('Kępno', 332),
    ('Łęka Opatowska', 332),
    ('Perzów', 332),
    ('Rychtal', 332),
    ('Trzcinica', 332),
    ('Koło (miasto)', 333),
    ('Babiak', 333),
    ('Chodów', 333),
    (
        'Dąbie (gmina w województwie wielkopolskim)',
        333
    ),
    ('Grzegorzew', 333),
    (
        'Kłodawa (gmina w województwie wielkopolskim)',
        333
    ),
    ('Koło (gmina wiejska)', 333),
    ('Kościelec', 333),
    ('Olszówka', 333),
    ('Osiek Mały', 333),
    ('Przedecz', 333),
    ('Golina', 334),
    ('Grodziec', 334),
    ('Kazimierz Biskupi', 334),
    ('Kleczew', 334),
    ('Kramsk', 334),
    ('Krzymów', 334),
    ('Rychwał', 334),
    (
        'Rzgów (gmina w województwie wielkopolskim)',
        334
    ),
    ('Skulsk', 334),
    ('Sompolno', 334),
    ('Stare Miasto', 334),
    ('Ślesin', 334),
    ('Wierzbinek', 334),
    ('Wilczyn', 334),
    ('Kościan', 335),
    ('Czempiń', 335),
    ('Kościan (gmina wiejska)', 335),
    ('Krzywiń', 335),
    ('Śmigiel', 335),
    ('Sulmierzyce', 336),
    ('Kobylin', 336),
    ('Koźmin Wielkopolski', 336),
    ('Krotoszyn', 336),
    ('Rozdrażew', 336),
    (
        'Zduny (gmina w województwie wielkopolskim)',
        336
    ),
    ('Krzemieniewo', 337),
    (
        'Lipno (gmina w województwie wielkopolskim)',
        337
    ),
    (
        'Osieczna (gmina w województwie wielkopolskim)',
        337
    ),
    ('Rydzyna', 337),
    ('Święciechowa', 337),
    ('Wijewo', 337),
    ('Włoszakowice', 337),
    ('Chrzypsko Wielkie', 338),
    ('Kwilcz', 338),
    ('Międzychód', 338),
    ('Sieraków', 338),
    ('Kuślin', 339),
    ('Lwówek', 339),
    ('Miedzichowo', 339),
    ('Nowy Tomyśl', 339),
    ('Opalenica', 339),
    ('Zbąszyń', 339),
    ('Oborniki', 340),
    ('Rogoźno', 340),
    ('Ryczywół', 340),
    ('Ostrów Wielkopolski', 341),
    ('Nowe Skalmierzyce', 341),
    ('Odolanów', 341),
    ('Ostrów Wielkopolski (gmina wiejska)', 341),
    ('Przygodzice', 341),
    ('Raszków', 341),
    ('Sieroszewice', 341),
    ('Sośnie', 341),
    ('Czajków', 342),
    ('Doruchów', 342),
    ('Grabów nad Prosną', 342),
    ('Kobyla Góra', 342),
    ('Kraszewice', 342),
    ('Mikstat', 342),
    ('Ostrzeszów', 342),
    ('Piła (miasto)', 343),
    ('Białośliwie', 343),
    ('Kaczory', 343),
    ('Łobżenica', 343),
    ('Miasteczko Krajeńskie', 343),
    (
        'Szydłowo (gmina w województwie wielkopolskim)',
        343
    ),
    ('Ujście', 343),
    ('Wyrzysk', 343),
    ('Wysoka', 343),
    ('Chocz', 344),
    (
        'Czermin (gmina w województwie wielkopolskim)',
        344
    ),
    ('Dobrzyca', 344),
    ('Gizałki', 344),
    ('Gołuchów', 344),
    ('Pleszew', 344),
    ('Luboń', 345),
    ('Puszczykowo', 345),
    ('Buk', 345),
    ('Czerwonak', 345),
    ('Dopiewo', 345),
    ('Kleszczewo', 345),
    ('Komorniki', 345),
    ('Kostrzyn', 345),
    ('Kórnik', 345),
    ('Mosina', 345),
    ('Murowana Goślina', 345),
    ('Pobiedziska', 345),
    (
        'Rokietnica (gmina w województwie wielkopolskim)',
        345
    ),
    ('Stęszew', 345),
    ('Suchy Las', 345),
    ('Swarzędz', 345),
    ('Tarnowo Podgórne', 345),
    ('Bojanowo', 346),
    ('Jutrosin', 346),
    ('Miejska Górka', 346),
    ('Pakosław', 346),
    ('Rawicz', 346),
    ('Słupca', 347),
    ('Lądek', 347),
    ('Orchowo', 347),
    ('Ostrowite', 347),
    ('Powidz', 347),
    ('Słupca (gmina wiejska)', 347),
    ('Strzałkowo', 347),
    ('Zagórów', 347),
    ('Obrzycko', 348),
    ('Duszniki', 348),
    ('Kaźmierz', 348),
    ('Obrzycko (gmina wiejska)', 348),
    ('Ostroróg', 348),
    (
        'Pniewy (gmina w województwie wielkopolskim)',
        348
    ),
    ('Szamotuły', 348),
    ('Wronki', 348),
    ('Dominowo', 349),
    ('Krzykosy', 349),
    ('Nowe Miasto nad Wartą', 349),
    ('Środa Wielkopolska', 349),
    ('Zaniemyśl', 349),
    (
        'Brodnica (gmina w województwie wielkopolskim)',
        350
    ),
    ('Dolsk', 350),
    ('Książ Wielkopolski', 350),
    ('Śrem', 350),
    ('Turek', 351),
    ('Brudzew', 351),
    (
        'Dobra (gmina w województwie wielkopolskim)',
        351
    ),
    ('Kawęczyn', 351),
    ('Malanów', 351),
    ('Przykona', 351),
    ('Tuliszków', 351),
    ('Turek (gmina wiejska)', 351),
    ('Władysławów', 351),
    ('Wągrowiec', 352),
    ('Damasławek', 352),
    ('Gołańcz', 352),
    ('Mieścisko', 352),
    ('Skoki', 352),
    ('Wapno', 352),
    ('Wągrowiec (gmina wiejska)', 352),
    ('Przemęt', 353),
    ('Siedlec', 353),
    ('Wolsztyn', 353),
    ('Kołaczkowo', 354),
    ('Miłosław', 354),
    ('Nekla', 354),
    ('Pyzdry', 354),
    ('Września', 354),
    ('Złotów', 355),
    ('Jastrowie', 355),
    ('Krajenka', 355),
    ('Lipka', 355),
    ('Okonek', 355),
    ('Tarnówka', 355),
    (
        'Zakrzewo (gmina w województwie wielkopolskim)',
        355
    ),
    ('Złotów (gmina wiejska)', 355),
    ('Kalisz', 356),
    ('Konin', 357),
    ('Leszno', 358),
    ('Poznań', 359),
    ('Białogard', 360),
    ('Białogard (gmina wiejska)', 360),
    ('Karlino', 360),
    ('Tychowo', 360),
    ('Bierzwnik', 361),
    ('Choszczno', 361),
    ('Drawno', 361),
    ('Krzęcin', 361),
    ('Pełczyce', 361),
    ('Recz', 361),
    ('Czaplinek', 362),
    ('Drawsko Pomorskie', 362),
    ('Kalisz Pomorski', 362),
    ('Wierzchowo', 362),
    ('Złocieniec', 362),
    ('Goleniów', 363),
    (
        'Maszewo (gmina w województwie zachodniopomorskim)',
        363
    ),
    ('Nowogard', 363),
    ('Osina', 363),
    ('Przybiernów', 363),
    ('Stepnica', 363),
    ('Brojce', 364),
    ('Gryfice', 364),
    ('Karnice', 364),
    ('Płoty', 364),
    ('Rewal', 364),
    ('Trzebiatów', 364),
    ('Banie', 365),
    ('Cedynia', 365),
    ('Chojna', 365),
    ('Gryfino', 365),
    ('Mieszkowice', 365),
    ('Moryń', 365),
    ('Stare Czarnowo', 365),
    ('Trzcińsko-Zdrój', 365),
    ('Widuchowa', 365),
    ('Dziwnów', 366),
    ('Golczewo', 366),
    ('Kamień Pomorski', 366),
    ('Międzyzdroje', 366),
    ('Świerzno', 366),
    ('Wolin', 366),
    ('Kołobrzeg', 367),
    ('Dygowo', 367),
    ('Gościno', 367),
    ('Kołobrzeg (gmina wiejska)', 367),
    ('Rymań', 367),
    ('Siemyśl', 367),
    ('Ustronie Morskie', 367),
    ('Będzino', 368),
    ('Biesiekierz', 368),
    ('Bobolice', 368),
    ('Manowo', 368),
    ('Mielno', 368),
    ('Polanów', 368),
    ('Sianów', 368),
    ('Świeszyno', 368),
    ('Barlinek', 369),
    ('Boleszkowice', 369),
    (
        'Dębno (gmina w województwie zachodniopomorskim)',
        369
    ),
    ('Myślibórz', 369),
    ('Nowogródek Pomorski', 369),
    ('Dobra (Szczecińska)', 370),
    ('Kołbaskowo', 370),
    ('Nowe Warpno', 370),
    ('Police', 370),
    ('Bielice', 371),
    ('Kozielice', 371),
    ('Lipiany', 371),
    ('Przelewice', 371),
    ('Pyrzyce', 371),
    ('Warnice', 371),
    ('Darłowo', 372),
    ('Sławno', 372),
    ('Darłowo (gmina wiejska)', 372),
    ('Malechowo', 372),
    ('Postomino', 372),
    (
        'Sławno (gmina wiejska w województwie zachodniopomorskim)',
        372
    ),
    ('Stargard', 373),
    ('Chociwel', 373),
    ('Dobrzany', 373),
    ('Dolice', 373),
    ('Ińsko', 373),
    ('Kobylanka', 373),
    ('Marianowo', 373),
    ('Stara Dąbrowa', 373),
    ('Stargard (gmina wiejska)', 373),
    ('Suchań', 373),
    ('Szczecinek', 374),
    ('Barwice', 374),
    ('Biały Bór', 374),
    ('Borne Sulinowo', 374),
    ('Grzmiąca', 374),
    ('Szczecinek (gmina wiejska)', 374),
    ('Świdwin', 375),
    ('Brzeżno', 375),
    ('Połczyn-Zdrój', 375),
    ('Rąbino', 375),
    ('Sławoborze', 375),
    ('Świdwin (gmina wiejska)', 375),
    ('Wałcz', 376),
    ('Człopa', 376),
    ('Mirosławiec', 376),
    ('Tuczno', 376),
    ('Wałcz (gmina wiejska)', 376),
    (
        'Dobra (gmina w województwie zachodniopomorskim)',
        377
    ),
    ('Łobez', 377),
    ('Radowo Małe', 377),
    ('Resko', 377),
    ('Węgorzyno', 377),
    ('Koszalin', 378),
    ('Szczecin', 379),
    ('Świnoujście', 380)