@url = http://localhost:3000


###authentification
@username = "🐱‍👤🐱‍👤🐱‍👤"
@password = "🦶🦶🦶🦶🦶🦶🦶420tak "
@email = "🐴🐓@.backdoor.com"
#Register a new user


###
POST {{url}}/registerUser HTTP/1.1
Content-Type: application/json

{
    "username": {{username}},
    "password": {{password}},
    "passwordConfirm":{{password}},
    "email": {{email}}
}
###
# code from email
@code = ntznw0U8wjxk3eW2RKFcfIDJPkz6aaOeMByvLnyoC3m7zCGqljRtVdNY4KAF3QbJikCsPYDZyX4ybN43WHvfp443s_GRMT0URkxjfQAK71vggQFenSY-MJvkjb1qcPo4cSKV-w
GET {{url}}/verify/{{code}} HTTP/1.1

#Login

###
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": {{username}},
    "password": {{password}}
}
### is logged in
@id = "102491262199805752"
@token = "5ziyJuZYn2dhDJe85DM2__U1WsljMP4XXb_zikB2wvcHfNgVMTKK9CnaAKWNbzWcarsVzwzNeYBvERsA3kjuYB1rlid33CCQoAtDoAszK8kx1T9XGIsg3IOkAlM0F9518PUQMg""
POST {{url}}/isLoggedIn HTTP/1.1
Content-Type: application/json

{
    "username": {{username}},
    "id": {{id}},
    "token": {{token}}
}
### logout
POST {{url}}/logout HTTP/1.1
Content-Type: application/json

{
    "username": {{username}},
    "id": {{id}},
    "token": {{token}}
}