@url = http://localhost:3000


###authentification
@firstName = "🐱‍👤🐱‍👤🐱‍👤"
@lastName = ""
@password = "🦶🦶🦶🦶🦶🦶🦶420tak "
@email = "🐴🐓@.backdoor.com"
#Register a new user


###
POST {{url}}/registerUser HTTP/1.1
Content-Type: application/json

{
    "firstName": {{firstName}},
    "lastName": {{lastName}},
    "password": {{password}},
    "passwordConfirm":{{password}},
    "email": {{email}}
}
###
# code from email
@code = z444wVjK9n4D29q9bj_E-VoIX9uxq7EJQdTze8gGWRozHjSeKORX2FmheYj9yHQmUqblwWh0hYyjU1zBRldCfp1Yu9C1SXJRXbP_cdqpMmZ04JJ7p48biNXFZsetffWHjJPaIQ
GET {{url}}/verify/{{code}} HTTP/1.1

#Login

###
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "email": {{email}},
    "password": {{password}}
}
### is logged in
@id = "102680768177781416"
@token = "cZJ9ocdCzwNRk7V1uzU1jmFcxQr9UYMebcEdAnlzKsf7LMKlSBVDX1oZEyJS4EWZdsHSsds6bnZx_xU0_S_xEK-is9WuyNFdv85om1pWUJhJgNbwOdrx1dIPB0mOvxH6hAY6sQ"
POST {{url}}/isLoggedIn HTTP/1.1
Content-Type: application/json

{
    "email": {{email}},
    "id": {{id}},
    "token": {{token}}
}
### logout
POST {{url}}/logout HTTP/1.1
Content-Type: application/json

{
    "email": {{email}},
    "id": {{id}},
    "token": {{token}}
}
###
GET {{url}}/test HTTP/1.1
###
GET {{url}}/wojewodztwa HTTP/1.1
### 
@wojId = 6
GET {{url}}/powiaty/{{wojId}} HTTP/1.1
###
@powId = 6
GET {{url}}/gminy/{{powId}} HTTP/1.1
